// Package dilithium5 implements the Dilithium5 (ML-DSA-87, NIST Category 5)
// post-quantum cryptography key type for Zytherion blockchain accounts.
//
// # Type URLs (used by interface registry and Any encoding)
//
//	/zytherion.crypto.dilithium5.PubKey
//	/zytherion.crypto.dilithium5.PrivKey
package dilithium5

import (
	"bytes"
	"compress/gzip"
	"fmt"
	"io"
	"sync"

	proto "github.com/cosmos/gogoproto/proto"
	"google.golang.org/protobuf/encoding/protowire"
)

const (
	// KeyType is the key algorithm name used in the keyring and CLI.
	KeyType = "dilithium5"

	// PubKeyTypeURL is the full protobuf type URL for Dilithium5 public keys.
	PubKeyTypeURL = "/zytherion.crypto.dilithium5.PubKey"

	// PrivKeyTypeURL is the full protobuf type URL for Dilithium5 private keys.
	PrivKeyTypeURL = "/zytherion.crypto.dilithium5.PrivKey"

	// Expected key sizes (from circl mode5 constants).
	PubKeySize  = 2592 // mode5.PublicKeySize
	PrivKeySize = 4864 // mode5.PrivateKeySize
	SigSize     = 4595 // mode5.SignatureSize
)

// ── Proto file descriptor ────────────────────────────────────────────────────
//
// rawDescGZIP is the gzip-compressed FileDescriptorProto for this package.
// It was generated by gen_descriptor.go and encodes:
//
//	syntax = "proto3";
//	package zytherion.crypto.dilithium5;
//	option go_package = "zytherion/crypto/dilithium5";
//	message PubKey  { bytes key = 1; }   // index 0
//	message PrivKey { bytes key = 1; }   // index 1
//
// Returning a valid descriptor from Descriptor() is required for:
//   - Cosmos SDK's unknownproto.RejectUnknownFieldsStrict (called by DefaultTxDecoder)
//   - gogoproto's jsonpb Any resolution during genesis tx JSON decode
var rawDescGZIP = []byte{
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xff, 0xe2, 0xd2, 0xa9, 0xaa, 0x2c, 0xc9,
	0x48, 0x2d, 0xca, 0xcc, 0xcf, 0xd3, 0x4f, 0x2e, 0xaa, 0x2c, 0x28, 0xc9, 0xd7, 0x4f, 0xc9, 0xcc,
	0xc9, 0x2c, 0xc9, 0xc8, 0x2c, 0xcd, 0x35, 0x45, 0x62, 0xea, 0x15, 0x14, 0xe5, 0x97, 0xe4, 0x0b,
	0x49, 0xc3, 0x55, 0xeb, 0x41, 0x54, 0xeb, 0x21, 0x94, 0x28, 0x89, 0x72, 0xb1, 0x05, 0x94, 0x26,
	0x79, 0xa7, 0x56, 0x0a, 0x71, 0x73, 0x31, 0x67, 0xa7, 0x56, 0x4a, 0x30, 0x2a, 0x30, 0x6a, 0xf0,
	0x28, 0x89, 0x71, 0xb1, 0x07, 0x14, 0x65, 0x96, 0xa1, 0x8b, 0x3b, 0xc9, 0x46, 0x49, 0xe3, 0xb1,
	0x3b, 0x89, 0x0d, 0x6c, 0xa3, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0x3f, 0xaf, 0x89, 0x96, 0xa1,
	0x00, 0x00, 0x00,
}

var (
	rawDescOnce sync.Once
	rawDescData []byte
)

// GetRawDescGZIP returns the raw gzip-compressed descriptor bytes.
// Used directly by Descriptor() on PubKey and PrivKey.
func GetRawDescGZIP() []byte { return rawDescGZIP }

// GetRawDesc returns the uncompressed FileDescriptorProto bytes (lazy-decoded once).
func GetRawDesc() []byte {
	rawDescOnce.Do(func() {
		r, err := gzip.NewReader(bytes.NewReader(rawDescGZIP))
		if err != nil {
			panic("dilithium5: failed to open gzip descriptor: " + err.Error())
		}
		defer r.Close()
		b, err := io.ReadAll(r)
		if err != nil {
			panic("dilithium5: failed to read gzip descriptor: " + err.Error())
		}
		rawDescData = b
	})
	return rawDescData
}

// ── PubKey ───────────────────────────────────────────────────────────────────

// PubKey is a Dilithium5 (ML-DSA-87) public key.
// It implements cryptotypes.PubKey and proto.Message.
//
// The protobuf wire encoding is:
//
//	message PubKey { bytes key = 1; }
//
// TypeURL: /zytherion.crypto.dilithium5.PubKey
type PubKey struct {
	// Key is the raw 2592-byte Dilithium5 public key.
	Key []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

// Ensure PubKey implements proto.Message.
var _ proto.Message = (*PubKey)(nil)

func (pk *PubKey) ProtoMessage() {}
func (pk *PubKey) Reset()        { *pk = PubKey{} }

// Descriptor returns the gzip-compressed FileDescriptorProto bytes for this
// package, and the path to PubKey within it (message index 0).
//
// Returning non-nil here is required by:
//   - Cosmos SDK's unknownproto.RejectUnknownFieldsStrict (called in DefaultTxDecoder)
//   - gogoproto's jsonpb AnyResolver when decoding genesis transactions
//
// Previously returned nil causing EOF: tx parse error during InitChain.
func (pk *PubKey) Descriptor() ([]byte, []int) { return rawDescGZIP, []int{0} }

func (pk *PubKey) String() string {
	if len(pk.Key) < 4 {
		return "dilithium5.PubKey{<empty>}"
	}
	return fmt.Sprintf("dilithium5.PubKey{%X...}", pk.Key[:4])
}

// Marshal implements gogoproto Marshaler — encodes as protobuf bytes field 1.
func (pk *PubKey) Marshal() ([]byte, error) {
	return marshalBytesField1(pk.Key), nil
}

// MarshalTo writes the encoded form into dAtA and returns bytes written.
func (pk *PubKey) MarshalTo(dAtA []byte) (int, error) {
	b := marshalBytesField1(pk.Key)
	copy(dAtA, b)
	return len(b), nil
}

// MarshalToSizedBuffer writes the encoded form backwards into dAtA.
func (pk *PubKey) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	b := marshalBytesField1(pk.Key)
	copy(dAtA[len(dAtA)-len(b):], b)
	return len(b), nil
}

// Unmarshal decodes dAtA as a protobuf-encoded PubKey.
func (pk *PubKey) Unmarshal(dAtA []byte) error {
	key, err := unmarshalBytesField1(dAtA)
	if err != nil {
		return fmt.Errorf("dilithium5.PubKey.Unmarshal: %w", err)
	}
	pk.Key = key
	return nil
}

// Size returns the serialized byte size.
func (pk *PubKey) Size() int { return sizeField1(len(pk.Key)) }

// Equal implements equality check for gogoproto.
func (pk *PubKey) Equal(other *PubKey) bool {
	return bytes.Equal(pk.Key, other.Key)
}

// ── PrivKey ──────────────────────────────────────────────────────────────────

// PrivKey is a Dilithium5 private key.
// It implements cryptotypes.PrivKey and proto.Message.
//
// The protobuf wire encoding is:
//
//	message PrivKey { bytes key = 1; }
//
// TypeURL: /zytherion.crypto.dilithium5.PrivKey
type PrivKey struct {
	// Key is the raw 4864-byte Dilithium5 private key.
	Key []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

var _ proto.Message = (*PrivKey)(nil)

func (sk *PrivKey) ProtoMessage() {}
func (sk *PrivKey) Reset()        { *sk = PrivKey{} }

// Descriptor returns the gzip-compressed FileDescriptorProto bytes for this
// package, and the path to PrivKey within it (message index 1).
func (sk *PrivKey) Descriptor() ([]byte, []int) { return rawDescGZIP, []int{1} }

func (sk *PrivKey) String() string { return "dilithium5.PrivKey{***REDACTED***}" }

func (sk *PrivKey) Marshal() ([]byte, error)           { return marshalBytesField1(sk.Key), nil }
func (sk *PrivKey) MarshalTo(dAtA []byte) (int, error) {
	b := marshalBytesField1(sk.Key)
	copy(dAtA, b)
	return len(b), nil
}
func (sk *PrivKey) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	b := marshalBytesField1(sk.Key)
	copy(dAtA[len(dAtA)-len(b):], b)
	return len(b), nil
}
func (sk *PrivKey) Unmarshal(dAtA []byte) error {
	key, err := unmarshalBytesField1(dAtA)
	if err != nil {
		return fmt.Errorf("dilithium5.PrivKey.Unmarshal: %w", err)
	}
	sk.Key = key
	return nil
}
func (sk *PrivKey) Size() int { return sizeField1(len(sk.Key)) }

// ── Proto registration ────────────────────────────────────────────────────────

func init() {
	// Register Dilithium5 key types with the gogoproto v1 registry.
	// This enables gogoproto.MessageName() to return the correct type name,
	// which is required by InterfaceRegistry.RegisterImplementations to compute
	// the type URL: "/" + gogoproto.MessageName(impl).
	//
	// Without this, RegisterImplementations would panic with type URL "/".
	proto.RegisterType((*PubKey)(nil), "zytherion.crypto.dilithium5.PubKey")
	proto.RegisterType((*PrivKey)(nil), "zytherion.crypto.dilithium5.PrivKey")
}

// ── Wire encoding helpers ─────────────────────────────────────────────────────
//
// These implement field 1, type bytes (length-delimited) encoding.
// Protobuf tag: field_number=1, wire_type=2 → tag byte = (1<<3)|2 = 10 = 0x0a

// marshalBytesField1 encodes a []byte as protobuf field 1 (bytes type).
func marshalBytesField1(b []byte) []byte {
	if len(b) == 0 {
		return nil
	}
	tag := protowire.AppendTag(nil, 1, protowire.BytesType)
	return protowire.AppendBytes(tag, b)
}

// unmarshalBytesField1 decodes the first bytes field (field number 1) from dAtA.
func unmarshalBytesField1(dAtA []byte) ([]byte, error) {
	for len(dAtA) > 0 {
		num, typ, n := protowire.ConsumeTag(dAtA)
		if n < 0 {
			return nil, protowire.ParseError(n)
		}
		dAtA = dAtA[n:]

		if num == 1 && typ == protowire.BytesType {
			v, n := protowire.ConsumeBytes(dAtA)
			if n < 0 {
				return nil, protowire.ParseError(n)
			}
			result := make([]byte, len(v))
			copy(result, v)
			return result, nil
		}

		// Skip unknown fields
		n = protowire.ConsumeFieldValue(num, typ, dAtA)
		if n < 0 {
			return nil, protowire.ParseError(n)
		}
		dAtA = dAtA[n:]
	}
	return nil, nil
}

// sizeField1 returns the serialized size of a bytes field with field number 1.
func sizeField1(dataLen int) int {
	if dataLen == 0 {
		return 0
	}
	// 1 byte tag + varint(len) + data
	tagLen := protowire.SizeTag(1)
	return tagLen + int(protowire.SizeVarint(uint64(dataLen))) + dataLen
}
