// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: zytherion/ibccollateral/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// MsgLockCollateral locks IBC collateral into the vault.
type MsgLockCollateral struct {
	Owner                string                                 `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	IbcDenom             string                                 `protobuf:"bytes,2,opt,name=ibc_denom,json=ibcDenom,proto3" json:"ibc_denom,omitempty"`
	Amount               github_com_cosmos_cosmos_sdk_types.Int `protobuf:"bytes,3,opt,name=amount,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Int" json:"amount"`
	XXX_NoUnkeyedLiteral struct{}                               `json:"-"`
	XXX_unrecognized     []byte                                 `json:"-"`
	XXX_sizecache        int32                                  `json:"-"`
}

func (m *MsgLockCollateral) Reset()         { *m = MsgLockCollateral{} }
func (m *MsgLockCollateral) String() string { return proto.CompactTextString(m) }
func (*MsgLockCollateral) ProtoMessage()    {}
func (*MsgLockCollateral) Descriptor() ([]byte, []int) {
	return fileDescriptor_8d5f67aed6b3e030, []int{0}
}
func (m *MsgLockCollateral) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgLockCollateral.Unmarshal(m, b)
}
func (m *MsgLockCollateral) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgLockCollateral.Marshal(b, m, deterministic)
}
func (m *MsgLockCollateral) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgLockCollateral.Merge(m, src)
}
func (m *MsgLockCollateral) XXX_Size() int {
	return xxx_messageInfo_MsgLockCollateral.Size(m)
}
func (m *MsgLockCollateral) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgLockCollateral.DiscardUnknown(m)
}

var xxx_messageInfo_MsgLockCollateral proto.InternalMessageInfo

func (m *MsgLockCollateral) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *MsgLockCollateral) GetIbcDenom() string {
	if m != nil {
		return m.IbcDenom
	}
	return ""
}

type MsgLockCollateralResponse struct {
	Owner                string                                 `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	IbcDenom             string                                 `protobuf:"bytes,2,opt,name=ibc_denom,json=ibcDenom,proto3" json:"ibc_denom,omitempty"`
	Locked               github_com_cosmos_cosmos_sdk_types.Int `protobuf:"bytes,3,opt,name=locked,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Int" json:"locked"`
	XXX_NoUnkeyedLiteral struct{}                               `json:"-"`
	XXX_unrecognized     []byte                                 `json:"-"`
	XXX_sizecache        int32                                  `json:"-"`
}

func (m *MsgLockCollateralResponse) Reset()         { *m = MsgLockCollateralResponse{} }
func (m *MsgLockCollateralResponse) String() string { return proto.CompactTextString(m) }
func (*MsgLockCollateralResponse) ProtoMessage()    {}
func (*MsgLockCollateralResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8d5f67aed6b3e030, []int{1}
}
func (m *MsgLockCollateralResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgLockCollateralResponse.Unmarshal(m, b)
}
func (m *MsgLockCollateralResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgLockCollateralResponse.Marshal(b, m, deterministic)
}
func (m *MsgLockCollateralResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgLockCollateralResponse.Merge(m, src)
}
func (m *MsgLockCollateralResponse) XXX_Size() int {
	return xxx_messageInfo_MsgLockCollateralResponse.Size(m)
}
func (m *MsgLockCollateralResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgLockCollateralResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgLockCollateralResponse proto.InternalMessageInfo

func (m *MsgLockCollateralResponse) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *MsgLockCollateralResponse) GetIbcDenom() string {
	if m != nil {
		return m.IbcDenom
	}
	return ""
}

// MsgUnlockCollateral releases previously locked collateral back to the owner.
type MsgUnlockCollateral struct {
	Owner                string                                 `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	IbcDenom             string                                 `protobuf:"bytes,2,opt,name=ibc_denom,json=ibcDenom,proto3" json:"ibc_denom,omitempty"`
	Amount               github_com_cosmos_cosmos_sdk_types.Int `protobuf:"bytes,3,opt,name=amount,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Int" json:"amount"`
	XXX_NoUnkeyedLiteral struct{}                               `json:"-"`
	XXX_unrecognized     []byte                                 `json:"-"`
	XXX_sizecache        int32                                  `json:"-"`
}

func (m *MsgUnlockCollateral) Reset()         { *m = MsgUnlockCollateral{} }
func (m *MsgUnlockCollateral) String() string { return proto.CompactTextString(m) }
func (*MsgUnlockCollateral) ProtoMessage()    {}
func (*MsgUnlockCollateral) Descriptor() ([]byte, []int) {
	return fileDescriptor_8d5f67aed6b3e030, []int{2}
}
func (m *MsgUnlockCollateral) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgUnlockCollateral.Unmarshal(m, b)
}
func (m *MsgUnlockCollateral) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgUnlockCollateral.Marshal(b, m, deterministic)
}
func (m *MsgUnlockCollateral) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUnlockCollateral.Merge(m, src)
}
func (m *MsgUnlockCollateral) XXX_Size() int {
	return xxx_messageInfo_MsgUnlockCollateral.Size(m)
}
func (m *MsgUnlockCollateral) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUnlockCollateral.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUnlockCollateral proto.InternalMessageInfo

func (m *MsgUnlockCollateral) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *MsgUnlockCollateral) GetIbcDenom() string {
	if m != nil {
		return m.IbcDenom
	}
	return ""
}

type MsgUnlockCollateralResponse struct {
	Owner                string                                 `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	IbcDenom             string                                 `protobuf:"bytes,2,opt,name=ibc_denom,json=ibcDenom,proto3" json:"ibc_denom,omitempty"`
	Unlocked             github_com_cosmos_cosmos_sdk_types.Int `protobuf:"bytes,3,opt,name=unlocked,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Int" json:"unlocked"`
	Remaining            github_com_cosmos_cosmos_sdk_types.Int `protobuf:"bytes,4,opt,name=remaining,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Int" json:"remaining"`
	XXX_NoUnkeyedLiteral struct{}                               `json:"-"`
	XXX_unrecognized     []byte                                 `json:"-"`
	XXX_sizecache        int32                                  `json:"-"`
}

func (m *MsgUnlockCollateralResponse) Reset()         { *m = MsgUnlockCollateralResponse{} }
func (m *MsgUnlockCollateralResponse) String() string { return proto.CompactTextString(m) }
func (*MsgUnlockCollateralResponse) ProtoMessage()    {}
func (*MsgUnlockCollateralResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8d5f67aed6b3e030, []int{3}
}
func (m *MsgUnlockCollateralResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgUnlockCollateralResponse.Unmarshal(m, b)
}
func (m *MsgUnlockCollateralResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgUnlockCollateralResponse.Marshal(b, m, deterministic)
}
func (m *MsgUnlockCollateralResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUnlockCollateralResponse.Merge(m, src)
}
func (m *MsgUnlockCollateralResponse) XXX_Size() int {
	return xxx_messageInfo_MsgUnlockCollateralResponse.Size(m)
}
func (m *MsgUnlockCollateralResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUnlockCollateralResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUnlockCollateralResponse proto.InternalMessageInfo

func (m *MsgUnlockCollateralResponse) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *MsgUnlockCollateralResponse) GetIbcDenom() string {
	if m != nil {
		return m.IbcDenom
	}
	return ""
}

func init() {
	proto.RegisterType((*MsgLockCollateral)(nil), "zytherion.ibccollateral.MsgLockCollateral")
	proto.RegisterType((*MsgLockCollateralResponse)(nil), "zytherion.ibccollateral.MsgLockCollateralResponse")
	proto.RegisterType((*MsgUnlockCollateral)(nil), "zytherion.ibccollateral.MsgUnlockCollateral")
	proto.RegisterType((*MsgUnlockCollateralResponse)(nil), "zytherion.ibccollateral.MsgUnlockCollateralResponse")
}

func init() { proto.RegisterFile("zytherion/ibccollateral/tx.proto", fileDescriptor_8d5f67aed6b3e030) }

var fileDescriptor_8d5f67aed6b3e030 = []byte{
	// 344 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0xa8, 0xaa, 0x2c, 0xc9,
	0x48, 0x2d, 0xca, 0xcc, 0xcf, 0xd3, 0xcf, 0x4c, 0x4a, 0x4e, 0xce, 0xcf, 0xc9, 0x49, 0x2c, 0x49,
	0x2d, 0x4a, 0xcc, 0xd1, 0x2f, 0xa9, 0xd0, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x12, 0x87, 0xab,
	0xd0, 0x43, 0x51, 0x21, 0x25, 0x92, 0x9e, 0x9f, 0x9e, 0x0f, 0x56, 0xa3, 0x0f, 0x62, 0x41, 0x94,
	0x2b, 0xf5, 0x31, 0x72, 0x09, 0xfa, 0x16, 0xa7, 0xfb, 0xe4, 0x27, 0x67, 0x3b, 0xc3, 0xd5, 0x0a,
	0x89, 0x70, 0xb1, 0xe6, 0x97, 0xe7, 0xa5, 0x16, 0x49, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0x41,
	0x38, 0x42, 0xd2, 0x5c, 0x9c, 0x99, 0x49, 0xc9, 0xf1, 0x29, 0xa9, 0x79, 0xf9, 0xb9, 0x12, 0x4c,
	0x60, 0x19, 0x8e, 0xcc, 0xa4, 0x64, 0x17, 0x10, 0x5f, 0xc8, 0x8d, 0x8b, 0x2d, 0x31, 0x37, 0xbf,
	0x34, 0xaf, 0x44, 0x82, 0x19, 0x24, 0xe3, 0xa4, 0x77, 0xe2, 0x9e, 0x3c, 0xc3, 0xad, 0x7b, 0xf2,
	0x6a, 0xe9, 0x99, 0x25, 0x19, 0xa5, 0x49, 0x7a, 0xc9, 0xf9, 0xb9, 0xfa, 0xc9, 0xf9, 0xc5, 0xb9,
	0xf9, 0xc5, 0x50, 0x4a, 0xb7, 0x38, 0x25, 0x5b, 0xbf, 0xa4, 0xb2, 0x20, 0xb5, 0x58, 0xcf, 0x33,
	0xaf, 0x24, 0x08, 0xaa, 0x5b, 0x69, 0x1a, 0x23, 0x97, 0x24, 0x86, 0x83, 0x82, 0x52, 0x8b, 0x0b,
	0xf2, 0xf3, 0x8a, 0x53, 0xc9, 0x74, 0x58, 0x4e, 0x7e, 0x72, 0x76, 0x6a, 0x0a, 0xb9, 0x0e, 0x83,
	0xe8, 0x56, 0x9a, 0xc0, 0xc8, 0x25, 0xec, 0x5b, 0x9c, 0x1e, 0x9a, 0x97, 0x33, 0x68, 0xc2, 0xea,
	0x15, 0x23, 0x97, 0x34, 0x16, 0x27, 0x51, 0x12, 0x5a, 0x5e, 0x5c, 0x1c, 0xa5, 0x79, 0x14, 0x85,
	0x17, 0x5c, 0xbf, 0x90, 0x0f, 0x17, 0x67, 0x51, 0x6a, 0x6e, 0x62, 0x66, 0x5e, 0x66, 0x5e, 0xba,
	0x04, 0x0b, 0x59, 0x86, 0x21, 0x0c, 0x30, 0x7a, 0xcf, 0xc8, 0xc5, 0xec, 0x5b, 0x9c, 0x2e, 0x54,
	0xc0, 0xc5, 0x87, 0x96, 0x5a, 0xb5, 0xf4, 0x70, 0xa4, 0x79, 0x3d, 0x8c, 0x84, 0x24, 0x65, 0x44,
	0xbc, 0x5a, 0x78, 0x30, 0x96, 0x71, 0x09, 0x60, 0xc4, 0xba, 0x0e, 0x3e, 0x73, 0xd0, 0x55, 0x4b,
	0x99, 0x90, 0xa2, 0x1a, 0x66, 0xaf, 0x93, 0x52, 0x14, 0x52, 0x76, 0xaf, 0x00, 0x65, 0x78, 0x5d,
	0xe4, 0x1c, 0x0f, 0x0a, 0xa4, 0x24, 0x36, 0x70, 0x36, 0x36, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff,
	0x36, 0x7d, 0x15, 0xba, 0x19, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	LockCollateral(ctx context.Context, in *MsgLockCollateral, opts ...grpc.CallOption) (*MsgLockCollateralResponse, error)
	UnlockCollateral(ctx context.Context, in *MsgUnlockCollateral, opts ...grpc.CallOption) (*MsgUnlockCollateralResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) LockCollateral(ctx context.Context, in *MsgLockCollateral, opts ...grpc.CallOption) (*MsgLockCollateralResponse, error) {
	out := new(MsgLockCollateralResponse)
	err := c.cc.Invoke(ctx, "/zytherion.ibccollateral.Msg/LockCollateral", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) UnlockCollateral(ctx context.Context, in *MsgUnlockCollateral, opts ...grpc.CallOption) (*MsgUnlockCollateralResponse, error) {
	out := new(MsgUnlockCollateralResponse)
	err := c.cc.Invoke(ctx, "/zytherion.ibccollateral.Msg/UnlockCollateral", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	LockCollateral(context.Context, *MsgLockCollateral) (*MsgLockCollateralResponse, error)
	UnlockCollateral(context.Context, *MsgUnlockCollateral) (*MsgUnlockCollateralResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) LockCollateral(ctx context.Context, req *MsgLockCollateral) (*MsgLockCollateralResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LockCollateral not implemented")
}
func (*UnimplementedMsgServer) UnlockCollateral(ctx context.Context, req *MsgUnlockCollateral) (*MsgUnlockCollateralResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnlockCollateral not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_LockCollateral_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgLockCollateral)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).LockCollateral(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/zytherion.ibccollateral.Msg/LockCollateral",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).LockCollateral(ctx, req.(*MsgLockCollateral))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_UnlockCollateral_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUnlockCollateral)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UnlockCollateral(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/zytherion.ibccollateral.Msg/UnlockCollateral",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UnlockCollateral(ctx, req.(*MsgUnlockCollateral))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "zytherion.ibccollateral.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LockCollateral",
			Handler:    _Msg_LockCollateral_Handler,
		},
		{
			MethodName: "UnlockCollateral",
			Handler:    _Msg_UnlockCollateral_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "zytherion/ibccollateral/tx.proto",
}
