// tx_deposit.go — InitCommitment CLI command (replaces old Deposit).
//
// Usage:
//
//	zytheriond tx privacy init-commitment <amount> --proof proof.json --from <key>
//
// Generate proof.json with:
//
//	go run ./tools/zkprove --amount 1000000 --pk keys/proving_key.bin --out proof.json
package cli

import (
	"fmt"
	"os"

	"github.com/cosmos/cosmos-sdk/client"
	"github.com/cosmos/cosmos-sdk/client/flags"
	"github.com/cosmos/cosmos-sdk/client/tx"
	"github.com/spf13/cobra"

	zkpkg "zytherion/x/privacy/zk"
	"zytherion/x/privacy/types"
)

// CmdInitCommitment returns a CLI command to initialize a privacy commitment.
//
// Deposits plaintext coins into the module escrow and registers a ZK-proven
// commitment on-chain. After this, the user's balance is tracked via commitments.
func CmdInitCommitment() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "init-commitment [amount] --proof <proof.json>",
		Short: "Deposit tokens and register a ZK commitment in the privacy module",
		Long: `Deposit tokens into the privacy module and register a ZK-proven commitment.

Step 1: Generate a proof for your deposit amount off-chain:

  go run ./tools/zkprove \
    --amount 1000000 \
    --pk keys/proving_key.bin \
    --out proof.json

Step 2: Submit the commitment on-chain:

  zytheriond tx privacy init-commitment 1000000uzyt \
    --proof proof.json \
    --from alice \
    --chain-id zytherion

The chain will verify the ZK proof before escrowing your tokens and storing
the 32-byte commitment. Your blinding factor (in proof.json) must be kept
secret — it is your "key" to spend the commitment later.`,
		Args: cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			clientCtx, err := client.GetClientTxContext(cmd)
			if err != nil {
				return err
			}

			amount := args[0]

			// ── 1. Load proof JSON ─────────────────────────────────────────────
			proofPath, _ := cmd.Flags().GetString(flagProofFile)
			if proofPath == "" {
				return fmt.Errorf("--proof flag is required (path to proof.json from zkprove tool)")
			}

			raw, err := os.ReadFile(proofPath)
			if err != nil {
				return fmt.Errorf("failed to read proof file %q: %w", proofPath, err)
			}

			proofData, err := zkpkg.DecodeProofJSON(raw)
			if err != nil {
				return fmt.Errorf("invalid proof JSON: %w", err)
			}

			// ── 2. Encode public inputs ────────────────────────────────────────
			if len(proofData.PublicInputs) < 2 {
				return fmt.Errorf("proof JSON must contain at least 2 public inputs")
			}
			publicInputs, err := zkpkg.EncodePublicInputs(
				proofData.PublicInputs[0],
				proofData.PublicInputs[1],
			)
			if err != nil {
				return fmt.Errorf("failed to encode public inputs: %w", err)
			}

			// ── 3. Build and broadcast message ────────────────────────────────
			creator := clientCtx.GetFromAddress().String()

			msg := types.NewMsgInitCommitment(
				creator,
				amount,
				proofData.Commitment,
				proofData.Proof,
				publicInputs,
			)
			if err := msg.ValidateBasic(); err != nil {
				return err
			}

			fmt.Printf("Submitting InitCommitment: amount=%s, proof=%s\n", amount, proofPath)
			return tx.GenerateOrBroadcastTxCLI(clientCtx, cmd.Flags(), msg)
		},
	}

	cmd.Flags().String(flagProofFile, "", "Path to proof.json generated by tools/zkprove (required)")
	_ = cmd.MarkFlagRequired(flagProofFile)
	flags.AddTxFlagsToCmd(cmd)

	return cmd
}

// CmdDeposit is a deprecated alias directing users to init-commitment.
func CmdDeposit() *cobra.Command {
	return &cobra.Command{
		Use:        "deposit",
		Deprecated: "Use 'init-commitment <amount> --proof proof.json' instead.",
		RunE: func(cmd *cobra.Command, args []string) error {
			return fmt.Errorf("deposit is deprecated. Use: zytheriond tx privacy init-commitment <amount> --proof proof.json --from <key>")
		},
	}
}
