// msg_deposit.go — SDK-specific methods for MsgDeposit.
//
// The struct definition and proto marshaling methods live in tx.pb.go.
// This file adds the sdk.Msg interface methods that are not generated by protoc.
package types

import (
	sdk "github.com/cosmos/cosmos-sdk/types"
	sdkerrors "github.com/cosmos/cosmos-sdk/types/errors"
)

// Ensure MsgDeposit satisfies the sdk.Msg interface.
var _ sdk.Msg = &MsgDeposit{}

const TypeMsgDeposit = "deposit"

// NewMsgDeposit constructs and returns a MsgDeposit.
func NewMsgDeposit(creator string, amount string) *MsgDeposit {
	return &MsgDeposit{
		Creator: creator,
		Amount:  amount,
	}
}

// Route implements sdk.Msg.
func (msg *MsgDeposit) Route() string { return RouterKey }

// Type implements sdk.Msg.
func (msg *MsgDeposit) Type() string { return TypeMsgDeposit }

// GetSigners implements sdk.Msg — the creator must sign.
func (msg *MsgDeposit) GetSigners() []sdk.AccAddress {
	addr, err := sdk.AccAddressFromBech32(msg.Creator)
	if err != nil {
		panic(err)
	}
	return []sdk.AccAddress{addr}
}

// GetSignBytes implements sdk.Msg.
func (msg *MsgDeposit) GetSignBytes() []byte {
	bz := ModuleCdc.MustMarshalJSON(msg)
	return sdk.MustSortJSON(bz)
}

// ValidateBasic implements sdk.Msg — performs stateless validation.
func (msg *MsgDeposit) ValidateBasic() error {
	if _, err := sdk.AccAddressFromBech32(msg.Creator); err != nil {
		return sdkerrors.Wrapf(ErrInvalidAddress, "invalid creator address: %s", err)
	}
	coin, err := sdk.ParseCoinNormalized(msg.Amount)
	if err != nil {
		return sdkerrors.Wrapf(ErrInvalidDepositAmount,
			"amount %q is not a valid sdk.Coin: %s", msg.Amount, err)
	}
	if !coin.IsPositive() {
		return sdkerrors.Wrapf(ErrInvalidDepositAmount,
			"deposit amount must be positive, got %s", msg.Amount)
	}
	return nil
}
