// msg_encrypted_transfer.go — SDK-specific methods for MsgEncryptedTransfer.
//
// The struct definition and proto marshaling methods live in tx.pb.go.
// This file adds the sdk.Msg interface methods that are not generated by protoc.
package types

import (
	sdk "github.com/cosmos/cosmos-sdk/types"
	sdkerrors "github.com/cosmos/cosmos-sdk/types/errors"
)

// Ensure MsgEncryptedTransfer satisfies the sdk.Msg interface.
var _ sdk.Msg = &MsgEncryptedTransfer{}

const TypeMsgEncryptedTransfer = "encrypted_transfer"

// NewMsgEncryptedTransfer constructs and returns a MsgEncryptedTransfer.
func NewMsgEncryptedTransfer(sender, recipient string, amountCiphertext []byte) *MsgEncryptedTransfer {
	return &MsgEncryptedTransfer{
		Sender:           sender,
		Recipient:        recipient,
		AmountCiphertext: amountCiphertext,
	}
}

// Route implements sdk.Msg.
func (msg *MsgEncryptedTransfer) Route() string { return RouterKey }

// Type implements sdk.Msg.
func (msg *MsgEncryptedTransfer) Type() string { return TypeMsgEncryptedTransfer }

// GetSigners implements sdk.Msg — the sender must sign.
func (msg *MsgEncryptedTransfer) GetSigners() []sdk.AccAddress {
	addr, err := sdk.AccAddressFromBech32(msg.Sender)
	if err != nil {
		panic(err)
	}
	return []sdk.AccAddress{addr}
}

// GetSignBytes implements sdk.Msg.
func (msg *MsgEncryptedTransfer) GetSignBytes() []byte {
	bz := ModuleCdc.MustMarshalJSON(msg)
	return sdk.MustSortJSON(bz)
}

// ValidateBasic implements sdk.Msg — performs stateless validation.
func (msg *MsgEncryptedTransfer) ValidateBasic() error {
	if _, err := sdk.AccAddressFromBech32(msg.Sender); err != nil {
		return sdkerrors.Wrapf(ErrInvalidAddress, "invalid sender address: %s", err)
	}
	if _, err := sdk.AccAddressFromBech32(msg.Recipient); err != nil {
		return sdkerrors.Wrapf(ErrInvalidAddress, "invalid recipient address: %s", err)
	}
	if len(msg.AmountCiphertext) == 0 {
		return ErrNoCiphertextProvided
	}
	return nil
}
