// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: zytherion/privacy/query.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "github.com/gogo/googleapis/google/api"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest is request type for the Query/Params RPC method.
type QueryParamsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8afd6ce3d33d5f2c, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryParamsRequest.Unmarshal(m, b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return xxx_messageInfo_QueryParamsRequest.Size(m)
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	// params holds all the parameters of this module.
	Params               Params   `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8afd6ce3d33d5f2c, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryParamsResponse.Unmarshal(m, b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return xxx_messageInfo_QueryParamsResponse.Size(m)
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

type QueryTFHEResultRequest struct {
	CommitmentHash       []byte   `protobuf:"bytes,1,opt,name=commitment_hash,json=commitmentHash,proto3" json:"commitment_hash,omitempty"`
	CommitmentHashHex    string   `protobuf:"bytes,2,opt,name=commitment_hash_hex,json=commitmentHashHex,proto3" json:"commitment_hash_hex,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryTFHEResultRequest) Reset()         { *m = QueryTFHEResultRequest{} }
func (m *QueryTFHEResultRequest) String() string { return proto.CompactTextString(m) }
func (*QueryTFHEResultRequest) ProtoMessage()    {}
func (*QueryTFHEResultRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8afd6ce3d33d5f2c, []int{2}
}
func (m *QueryTFHEResultRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryTFHEResultRequest.Unmarshal(m, b)
}
func (m *QueryTFHEResultRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryTFHEResultRequest.Marshal(b, m, deterministic)
}
func (m *QueryTFHEResultRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryTFHEResultRequest.Merge(m, src)
}
func (m *QueryTFHEResultRequest) XXX_Size() int {
	return xxx_messageInfo_QueryTFHEResultRequest.Size(m)
}
func (m *QueryTFHEResultRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryTFHEResultRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryTFHEResultRequest proto.InternalMessageInfo

func (m *QueryTFHEResultRequest) GetCommitmentHash() []byte {
	if m != nil {
		return m.CommitmentHash
	}
	return nil
}

func (m *QueryTFHEResultRequest) GetCommitmentHashHex() string {
	if m != nil {
		return m.CommitmentHashHex
	}
	return ""
}

type QueryTFHEResultResponse struct {
	CommitmentHash       []byte   `protobuf:"bytes,1,opt,name=commitment_hash,json=commitmentHash,proto3" json:"commitment_hash,omitempty"`
	ResultCiphertext     []byte   `protobuf:"bytes,2,opt,name=result_ciphertext,json=resultCiphertext,proto3" json:"result_ciphertext,omitempty"`
	ReconstructedFrom    uint32   `protobuf:"varint,3,opt,name=reconstructed_from,json=reconstructedFrom,proto3" json:"reconstructed_from,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryTFHEResultResponse) Reset()         { *m = QueryTFHEResultResponse{} }
func (m *QueryTFHEResultResponse) String() string { return proto.CompactTextString(m) }
func (*QueryTFHEResultResponse) ProtoMessage()    {}
func (*QueryTFHEResultResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8afd6ce3d33d5f2c, []int{3}
}
func (m *QueryTFHEResultResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryTFHEResultResponse.Unmarshal(m, b)
}
func (m *QueryTFHEResultResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryTFHEResultResponse.Marshal(b, m, deterministic)
}
func (m *QueryTFHEResultResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryTFHEResultResponse.Merge(m, src)
}
func (m *QueryTFHEResultResponse) XXX_Size() int {
	return xxx_messageInfo_QueryTFHEResultResponse.Size(m)
}
func (m *QueryTFHEResultResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryTFHEResultResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryTFHEResultResponse proto.InternalMessageInfo

func (m *QueryTFHEResultResponse) GetCommitmentHash() []byte {
	if m != nil {
		return m.CommitmentHash
	}
	return nil
}

func (m *QueryTFHEResultResponse) GetResultCiphertext() []byte {
	if m != nil {
		return m.ResultCiphertext
	}
	return nil
}

func (m *QueryTFHEResultResponse) GetReconstructedFrom() uint32 {
	if m != nil {
		return m.ReconstructedFrom
	}
	return 0
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "zytherion.privacy.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "zytherion.privacy.QueryParamsResponse")
	proto.RegisterType((*QueryTFHEResultRequest)(nil), "zytherion.privacy.QueryTFHEResultRequest")
	proto.RegisterType((*QueryTFHEResultResponse)(nil), "zytherion.privacy.QueryTFHEResultResponse")
}

func init() { proto.RegisterFile("zytherion/privacy/query.proto", fileDescriptor_8afd6ce3d33d5f2c) }

var fileDescriptor_8afd6ce3d33d5f2c = []byte{
	// 418 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0xc5, 0x01, 0x22, 0xb1, 0x84, 0x0f, 0x6f, 0x22, 0x48, 0x1c, 0x3e, 0x82, 0x25, 0x20, 0x80,
	0xf0, 0x8a, 0x70, 0x88, 0x38, 0x21, 0x05, 0x11, 0xe5, 0x84, 0xc0, 0xe2, 0xd4, 0x8b, 0xb5, 0x75,
	0x27, 0xb6, 0xa5, 0xd8, 0xeb, 0xec, 0xae, 0x23, 0x3b, 0x55, 0x2f, 0xfd, 0x0b, 0xbd, 0xf7, 0xd4,
	0x53, 0x7f, 0x49, 0xef, 0xbd, 0xf7, 0xd4, 0x1f, 0x52, 0x65, 0x6d, 0x25, 0x4a, 0x9d, 0xa8, 0xb9,
	0xad, 0xe6, 0xbd, 0x37, 0xef, 0xed, 0xcc, 0xa0, 0xd7, 0xf3, 0x4c, 0xfa, 0xc0, 0x03, 0x16, 0x91,
	0x98, 0x07, 0x33, 0xea, 0x66, 0x64, 0x9a, 0x00, 0xcf, 0xac, 0x98, 0x33, 0xc9, 0xb0, 0xbe, 0x84,
	0xad, 0x02, 0x36, 0x1a, 0x1e, 0xf3, 0x98, 0x42, 0xc9, 0xe2, 0x95, 0x13, 0x8d, 0x57, 0x1e, 0x63,
	0xde, 0x04, 0x08, 0x8d, 0x03, 0x42, 0xa3, 0x88, 0x49, 0x2a, 0x03, 0x16, 0x89, 0x02, 0x7d, 0x53,
	0x76, 0x89, 0x29, 0xa7, 0x61, 0x81, 0x9b, 0x0d, 0x84, 0xff, 0x2d, 0x5c, 0xff, 0xaa, 0xa2, 0x0d,
	0xd3, 0x04, 0x84, 0x34, 0xff, 0xa0, 0xfa, 0x5a, 0x55, 0xc4, 0x2c, 0x12, 0x80, 0xfb, 0xa8, 0x9a,
	0x8b, 0x9b, 0x5a, 0x47, 0xeb, 0x3e, 0xee, 0xb5, 0xac, 0x52, 0x48, 0x2b, 0x97, 0x0c, 0x1e, 0x5c,
	0x5c, 0xbd, 0xbd, 0x67, 0x17, 0x74, 0x73, 0x8a, 0x5e, 0xa8, 0x7e, 0xff, 0x87, 0xa3, 0xdf, 0x36,
	0x88, 0x64, 0x22, 0x0b, 0x27, 0xfc, 0x11, 0x3d, 0x73, 0x59, 0x18, 0x06, 0x32, 0x84, 0x48, 0x3a,
	0x3e, 0x15, 0xbe, 0xea, 0x5d, 0xb3, 0x9f, 0xae, 0xca, 0x23, 0x2a, 0x7c, 0x6c, 0xa1, 0xfa, 0x2d,
	0xa2, 0xe3, 0x43, 0xda, 0xac, 0x74, 0xb4, 0xee, 0x23, 0x5b, 0x5f, 0x27, 0x8f, 0x20, 0x35, 0x4f,
	0x35, 0xf4, 0xb2, 0xe4, 0x59, 0xfc, 0x63, 0x67, 0xd3, 0x2f, 0x48, 0xe7, 0x4a, 0xea, 0xb8, 0x41,
	0xec, 0x03, 0x97, 0x90, 0x4a, 0x65, 0x59, 0xb3, 0x9f, 0xe7, 0xc0, 0xaf, 0x65, 0x1d, 0x7f, 0x45,
	0x98, 0x83, 0xcb, 0x22, 0x21, 0x79, 0xe2, 0x4a, 0x38, 0x70, 0xc6, 0x9c, 0x85, 0xcd, 0xfb, 0x1d,
	0xad, 0xfb, 0xc4, 0xd6, 0xd7, 0x90, 0x21, 0x67, 0x61, 0xef, 0xbc, 0x82, 0x1e, 0xaa, 0x80, 0x78,
	0x8e, 0xaa, 0xf9, 0xd4, 0xf0, 0xfb, 0x0d, 0x03, 0x2d, 0xaf, 0xc7, 0xf8, 0x70, 0x17, 0x2d, 0xff,
	0xa7, 0xf9, 0xee, 0xf8, 0xf2, 0xfa, 0xa4, 0xd2, 0xc6, 0x2d, 0xb2, 0xed, 0x0a, 0xf0, 0x99, 0x86,
	0xd0, 0x6a, 0x42, 0xf8, 0xd3, 0xb6, 0xce, 0xa5, 0xcd, 0x19, 0x9f, 0x77, 0xa1, 0x16, 0x41, 0x7e,
	0xaa, 0x20, 0x3f, 0x70, 0x7f, 0x43, 0x90, 0xd9, 0x37, 0x22, 0xc7, 0x3e, 0x90, 0x7c, 0x9e, 0xe4,
	0x70, 0xc3, 0x96, 0x8f, 0x06, 0xed, 0xbd, 0xd6, 0x4a, 0x99, 0x2e, 0xb5, 0x32, 0x8b, 0x41, 0xec,
	0x57, 0xd5, 0x29, 0x7f, 0xbf, 0x09, 0x00, 0x00, 0xff, 0xff, 0x4d, 0x3c, 0x50, 0x28, 0x52, 0x03,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// TFHEResult queries the reconstructed TFHE ciphertext result for a commitment.
	TFHEResult(ctx context.Context, in *QueryTFHEResultRequest, opts ...grpc.CallOption) (*QueryTFHEResultResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/zytherion.privacy.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) TFHEResult(ctx context.Context, in *QueryTFHEResultRequest, opts ...grpc.CallOption) (*QueryTFHEResultResponse, error) {
	out := new(QueryTFHEResultResponse)
	err := c.cc.Invoke(ctx, "/zytherion.privacy.Query/TFHEResult", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// TFHEResult queries the reconstructed TFHE ciphertext result for a commitment.
	TFHEResult(context.Context, *QueryTFHEResultRequest) (*QueryTFHEResultResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) TFHEResult(ctx context.Context, req *QueryTFHEResultRequest) (*QueryTFHEResultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TFHEResult not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/zytherion.privacy.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_TFHEResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryTFHEResultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).TFHEResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/zytherion.privacy.Query/TFHEResult",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).TFHEResult(ctx, req.(*QueryTFHEResultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "zytherion.privacy.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "TFHEResult",
			Handler:    _Query_TFHEResult_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "zytherion/privacy/query.proto",
}
