// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: zytherion/stablecoin/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// MsgMintZYTD mints ZYTD stablecoin against locked collateral.
type MsgMintZYTD struct {
	Sender                string                                 `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	IbcDenom              string                                 `protobuf:"bytes,2,opt,name=ibc_denom,json=ibcDenom,proto3" json:"ibc_denom,omitempty"`
	CollateralAmount      github_com_cosmos_cosmos_sdk_types.Int `protobuf:"bytes,3,opt,name=collateral_amount,json=collateralAmount,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Int" json:"collateral_amount"`
	RequestedZytd         github_com_cosmos_cosmos_sdk_types.Int `protobuf:"bytes,4,opt,name=requested_zytd,json=requestedZytd,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Int" json:"requested_zytd"`
	ExpirationBlockHeight int64                                  `protobuf:"varint,5,opt,name=expiration_block_height,json=expirationBlockHeight,proto3" json:"expiration_block_height,omitempty"`
	Dilithium5PubKey      []byte                                 `protobuf:"bytes,6,opt,name=dilithium5_pub_key,json=dilithium5PubKey,proto3" json:"dilithium5_pub_key,omitempty"`
	Dilithium5Sig         []byte                                 `protobuf:"bytes,7,opt,name=dilithium5_sig,json=dilithium5Sig,proto3" json:"dilithium5_sig,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}                               `json:"-"`
	XXX_unrecognized      []byte                                 `json:"-"`
	XXX_sizecache         int32                                  `json:"-"`
}

func (m *MsgMintZYTD) Reset()         { *m = MsgMintZYTD{} }
func (m *MsgMintZYTD) String() string { return proto.CompactTextString(m) }
func (*MsgMintZYTD) ProtoMessage()    {}
func (*MsgMintZYTD) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fa1584706260d29, []int{0}
}
func (m *MsgMintZYTD) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgMintZYTD.Unmarshal(m, b)
}
func (m *MsgMintZYTD) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgMintZYTD.Marshal(b, m, deterministic)
}
func (m *MsgMintZYTD) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgMintZYTD.Merge(m, src)
}
func (m *MsgMintZYTD) XXX_Size() int {
	return xxx_messageInfo_MsgMintZYTD.Size(m)
}
func (m *MsgMintZYTD) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgMintZYTD.DiscardUnknown(m)
}

var xxx_messageInfo_MsgMintZYTD proto.InternalMessageInfo

func (m *MsgMintZYTD) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

func (m *MsgMintZYTD) GetIbcDenom() string {
	if m != nil {
		return m.IbcDenom
	}
	return ""
}

func (m *MsgMintZYTD) GetExpirationBlockHeight() int64 {
	if m != nil {
		return m.ExpirationBlockHeight
	}
	return 0
}

func (m *MsgMintZYTD) GetDilithium5PubKey() []byte {
	if m != nil {
		return m.Dilithium5PubKey
	}
	return nil
}

func (m *MsgMintZYTD) GetDilithium5Sig() []byte {
	if m != nil {
		return m.Dilithium5Sig
	}
	return nil
}

type MsgMintZYTDResponse struct {
	MintedAmount         github_com_cosmos_cosmos_sdk_types.Int `protobuf:"bytes,1,opt,name=minted_amount,json=mintedAmount,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Int" json:"minted_amount"`
	XXX_NoUnkeyedLiteral struct{}                               `json:"-"`
	XXX_unrecognized     []byte                                 `json:"-"`
	XXX_sizecache        int32                                  `json:"-"`
}

func (m *MsgMintZYTDResponse) Reset()         { *m = MsgMintZYTDResponse{} }
func (m *MsgMintZYTDResponse) String() string { return proto.CompactTextString(m) }
func (*MsgMintZYTDResponse) ProtoMessage()    {}
func (*MsgMintZYTDResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fa1584706260d29, []int{1}
}
func (m *MsgMintZYTDResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgMintZYTDResponse.Unmarshal(m, b)
}
func (m *MsgMintZYTDResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgMintZYTDResponse.Marshal(b, m, deterministic)
}
func (m *MsgMintZYTDResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgMintZYTDResponse.Merge(m, src)
}
func (m *MsgMintZYTDResponse) XXX_Size() int {
	return xxx_messageInfo_MsgMintZYTDResponse.Size(m)
}
func (m *MsgMintZYTDResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgMintZYTDResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgMintZYTDResponse proto.InternalMessageInfo

// MsgBurnZYTD burns ZYTD and unlocks proportional collateral.
type MsgBurnZYTD struct {
	Sender                string                                 `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	IbcDenom              string                                 `protobuf:"bytes,2,opt,name=ibc_denom,json=ibcDenom,proto3" json:"ibc_denom,omitempty"`
	ZytdAmount            github_com_cosmos_cosmos_sdk_types.Int `protobuf:"bytes,3,opt,name=zytd_amount,json=zytdAmount,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Int" json:"zytd_amount"`
	ExpirationBlockHeight int64                                  `protobuf:"varint,4,opt,name=expiration_block_height,json=expirationBlockHeight,proto3" json:"expiration_block_height,omitempty"`
	Dilithium5PubKey      []byte                                 `protobuf:"bytes,5,opt,name=dilithium5_pub_key,json=dilithium5PubKey,proto3" json:"dilithium5_pub_key,omitempty"`
	Dilithium5Sig         []byte                                 `protobuf:"bytes,6,opt,name=dilithium5_sig,json=dilithium5Sig,proto3" json:"dilithium5_sig,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}                               `json:"-"`
	XXX_unrecognized      []byte                                 `json:"-"`
	XXX_sizecache         int32                                  `json:"-"`
}

func (m *MsgBurnZYTD) Reset()         { *m = MsgBurnZYTD{} }
func (m *MsgBurnZYTD) String() string { return proto.CompactTextString(m) }
func (*MsgBurnZYTD) ProtoMessage()    {}
func (*MsgBurnZYTD) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fa1584706260d29, []int{2}
}
func (m *MsgBurnZYTD) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgBurnZYTD.Unmarshal(m, b)
}
func (m *MsgBurnZYTD) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgBurnZYTD.Marshal(b, m, deterministic)
}
func (m *MsgBurnZYTD) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgBurnZYTD.Merge(m, src)
}
func (m *MsgBurnZYTD) XXX_Size() int {
	return xxx_messageInfo_MsgBurnZYTD.Size(m)
}
func (m *MsgBurnZYTD) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgBurnZYTD.DiscardUnknown(m)
}

var xxx_messageInfo_MsgBurnZYTD proto.InternalMessageInfo

func (m *MsgBurnZYTD) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

func (m *MsgBurnZYTD) GetIbcDenom() string {
	if m != nil {
		return m.IbcDenom
	}
	return ""
}

func (m *MsgBurnZYTD) GetExpirationBlockHeight() int64 {
	if m != nil {
		return m.ExpirationBlockHeight
	}
	return 0
}

func (m *MsgBurnZYTD) GetDilithium5PubKey() []byte {
	if m != nil {
		return m.Dilithium5PubKey
	}
	return nil
}

func (m *MsgBurnZYTD) GetDilithium5Sig() []byte {
	if m != nil {
		return m.Dilithium5Sig
	}
	return nil
}

type MsgBurnZYTDResponse struct {
	UnlockedAmount       github_com_cosmos_cosmos_sdk_types.Int `protobuf:"bytes,1,opt,name=unlocked_amount,json=unlockedAmount,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Int" json:"unlocked_amount"`
	XXX_NoUnkeyedLiteral struct{}                               `json:"-"`
	XXX_unrecognized     []byte                                 `json:"-"`
	XXX_sizecache        int32                                  `json:"-"`
}

func (m *MsgBurnZYTDResponse) Reset()         { *m = MsgBurnZYTDResponse{} }
func (m *MsgBurnZYTDResponse) String() string { return proto.CompactTextString(m) }
func (*MsgBurnZYTDResponse) ProtoMessage()    {}
func (*MsgBurnZYTDResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fa1584706260d29, []int{3}
}
func (m *MsgBurnZYTDResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgBurnZYTDResponse.Unmarshal(m, b)
}
func (m *MsgBurnZYTDResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgBurnZYTDResponse.Marshal(b, m, deterministic)
}
func (m *MsgBurnZYTDResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgBurnZYTDResponse.Merge(m, src)
}
func (m *MsgBurnZYTDResponse) XXX_Size() int {
	return xxx_messageInfo_MsgBurnZYTDResponse.Size(m)
}
func (m *MsgBurnZYTDResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgBurnZYTDResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgBurnZYTDResponse proto.InternalMessageInfo

// MsgLiquidate liquidates an undercollateralized position.
type MsgLiquidate struct {
	Liquidator            string   `protobuf:"bytes,1,opt,name=liquidator,proto3" json:"liquidator,omitempty"`
	TargetOwner           string   `protobuf:"bytes,2,opt,name=target_owner,json=targetOwner,proto3" json:"target_owner,omitempty"`
	IbcDenom              string   `protobuf:"bytes,3,opt,name=ibc_denom,json=ibcDenom,proto3" json:"ibc_denom,omitempty"`
	ExpirationBlockHeight int64    `protobuf:"varint,4,opt,name=expiration_block_height,json=expirationBlockHeight,proto3" json:"expiration_block_height,omitempty"`
	Dilithium5PubKey      []byte   `protobuf:"bytes,5,opt,name=dilithium5_pub_key,json=dilithium5PubKey,proto3" json:"dilithium5_pub_key,omitempty"`
	Dilithium5Sig         []byte   `protobuf:"bytes,6,opt,name=dilithium5_sig,json=dilithium5Sig,proto3" json:"dilithium5_sig,omitempty"`
	XXX_NoUnkeyedLiteral  struct{} `json:"-"`
	XXX_unrecognized      []byte   `json:"-"`
	XXX_sizecache         int32    `json:"-"`
}

func (m *MsgLiquidate) Reset()         { *m = MsgLiquidate{} }
func (m *MsgLiquidate) String() string { return proto.CompactTextString(m) }
func (*MsgLiquidate) ProtoMessage()    {}
func (*MsgLiquidate) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fa1584706260d29, []int{4}
}
func (m *MsgLiquidate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgLiquidate.Unmarshal(m, b)
}
func (m *MsgLiquidate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgLiquidate.Marshal(b, m, deterministic)
}
func (m *MsgLiquidate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgLiquidate.Merge(m, src)
}
func (m *MsgLiquidate) XXX_Size() int {
	return xxx_messageInfo_MsgLiquidate.Size(m)
}
func (m *MsgLiquidate) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgLiquidate.DiscardUnknown(m)
}

var xxx_messageInfo_MsgLiquidate proto.InternalMessageInfo

func (m *MsgLiquidate) GetLiquidator() string {
	if m != nil {
		return m.Liquidator
	}
	return ""
}

func (m *MsgLiquidate) GetTargetOwner() string {
	if m != nil {
		return m.TargetOwner
	}
	return ""
}

func (m *MsgLiquidate) GetIbcDenom() string {
	if m != nil {
		return m.IbcDenom
	}
	return ""
}

func (m *MsgLiquidate) GetExpirationBlockHeight() int64 {
	if m != nil {
		return m.ExpirationBlockHeight
	}
	return 0
}

func (m *MsgLiquidate) GetDilithium5PubKey() []byte {
	if m != nil {
		return m.Dilithium5PubKey
	}
	return nil
}

func (m *MsgLiquidate) GetDilithium5Sig() []byte {
	if m != nil {
		return m.Dilithium5Sig
	}
	return nil
}

type MsgLiquidateResponse struct {
	SeizedAmount         github_com_cosmos_cosmos_sdk_types.Int `protobuf:"bytes,1,opt,name=seized_amount,json=seizedAmount,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Int" json:"seized_amount"`
	XXX_NoUnkeyedLiteral struct{}                               `json:"-"`
	XXX_unrecognized     []byte                                 `json:"-"`
	XXX_sizecache        int32                                  `json:"-"`
}

func (m *MsgLiquidateResponse) Reset()         { *m = MsgLiquidateResponse{} }
func (m *MsgLiquidateResponse) String() string { return proto.CompactTextString(m) }
func (*MsgLiquidateResponse) ProtoMessage()    {}
func (*MsgLiquidateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fa1584706260d29, []int{5}
}
func (m *MsgLiquidateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgLiquidateResponse.Unmarshal(m, b)
}
func (m *MsgLiquidateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgLiquidateResponse.Marshal(b, m, deterministic)
}
func (m *MsgLiquidateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgLiquidateResponse.Merge(m, src)
}
func (m *MsgLiquidateResponse) XXX_Size() int {
	return xxx_messageInfo_MsgLiquidateResponse.Size(m)
}
func (m *MsgLiquidateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgLiquidateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgLiquidateResponse proto.InternalMessageInfo

// MsgRegisterZYTDKey registers a Dilithium5 public key.
type MsgRegisterZYTDKey struct {
	Sender                string   `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	Dilithium5PubKey      []byte   `protobuf:"bytes,2,opt,name=dilithium5_pub_key,json=dilithium5PubKey,proto3" json:"dilithium5_pub_key,omitempty"`
	ExpirationBlockHeight int64    `protobuf:"varint,3,opt,name=expiration_block_height,json=expirationBlockHeight,proto3" json:"expiration_block_height,omitempty"`
	XXX_NoUnkeyedLiteral  struct{} `json:"-"`
	XXX_unrecognized      []byte   `json:"-"`
	XXX_sizecache         int32    `json:"-"`
}

func (m *MsgRegisterZYTDKey) Reset()         { *m = MsgRegisterZYTDKey{} }
func (m *MsgRegisterZYTDKey) String() string { return proto.CompactTextString(m) }
func (*MsgRegisterZYTDKey) ProtoMessage()    {}
func (*MsgRegisterZYTDKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fa1584706260d29, []int{6}
}
func (m *MsgRegisterZYTDKey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgRegisterZYTDKey.Unmarshal(m, b)
}
func (m *MsgRegisterZYTDKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgRegisterZYTDKey.Marshal(b, m, deterministic)
}
func (m *MsgRegisterZYTDKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRegisterZYTDKey.Merge(m, src)
}
func (m *MsgRegisterZYTDKey) XXX_Size() int {
	return xxx_messageInfo_MsgRegisterZYTDKey.Size(m)
}
func (m *MsgRegisterZYTDKey) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRegisterZYTDKey.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRegisterZYTDKey proto.InternalMessageInfo

func (m *MsgRegisterZYTDKey) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

func (m *MsgRegisterZYTDKey) GetDilithium5PubKey() []byte {
	if m != nil {
		return m.Dilithium5PubKey
	}
	return nil
}

func (m *MsgRegisterZYTDKey) GetExpirationBlockHeight() int64 {
	if m != nil {
		return m.ExpirationBlockHeight
	}
	return 0
}

type MsgRegisterZYTDKeyResponse struct {
	RegisteredPubKeyHash string   `protobuf:"bytes,1,opt,name=registered_pub_key_hash,json=registeredPubKeyHash,proto3" json:"registered_pub_key_hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgRegisterZYTDKeyResponse) Reset()         { *m = MsgRegisterZYTDKeyResponse{} }
func (m *MsgRegisterZYTDKeyResponse) String() string { return proto.CompactTextString(m) }
func (*MsgRegisterZYTDKeyResponse) ProtoMessage()    {}
func (*MsgRegisterZYTDKeyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1fa1584706260d29, []int{7}
}
func (m *MsgRegisterZYTDKeyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgRegisterZYTDKeyResponse.Unmarshal(m, b)
}
func (m *MsgRegisterZYTDKeyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgRegisterZYTDKeyResponse.Marshal(b, m, deterministic)
}
func (m *MsgRegisterZYTDKeyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRegisterZYTDKeyResponse.Merge(m, src)
}
func (m *MsgRegisterZYTDKeyResponse) XXX_Size() int {
	return xxx_messageInfo_MsgRegisterZYTDKeyResponse.Size(m)
}
func (m *MsgRegisterZYTDKeyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRegisterZYTDKeyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRegisterZYTDKeyResponse proto.InternalMessageInfo

func (m *MsgRegisterZYTDKeyResponse) GetRegisteredPubKeyHash() string {
	if m != nil {
		return m.RegisteredPubKeyHash
	}
	return ""
}

func init() {
	proto.RegisterType((*MsgMintZYTD)(nil), "zytherion.stablecoin.MsgMintZYTD")
	proto.RegisterType((*MsgMintZYTDResponse)(nil), "zytherion.stablecoin.MsgMintZYTDResponse")
	proto.RegisterType((*MsgBurnZYTD)(nil), "zytherion.stablecoin.MsgBurnZYTD")
	proto.RegisterType((*MsgBurnZYTDResponse)(nil), "zytherion.stablecoin.MsgBurnZYTDResponse")
	proto.RegisterType((*MsgLiquidate)(nil), "zytherion.stablecoin.MsgLiquidate")
	proto.RegisterType((*MsgLiquidateResponse)(nil), "zytherion.stablecoin.MsgLiquidateResponse")
	proto.RegisterType((*MsgRegisterZYTDKey)(nil), "zytherion.stablecoin.MsgRegisterZYTDKey")
	proto.RegisterType((*MsgRegisterZYTDKeyResponse)(nil), "zytherion.stablecoin.MsgRegisterZYTDKeyResponse")
}

func init() { proto.RegisterFile("zytherion/stablecoin/tx.proto", fileDescriptor_1fa1584706260d29) }

var fileDescriptor_1fa1584706260d29 = []byte{
	// 643 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x95, 0xcb, 0x6e, 0xd3, 0x40,
	0x14, 0x86, 0x71, 0xdd, 0x86, 0xf6, 0x34, 0xbd, 0x30, 0x04, 0x6a, 0x05, 0xe8, 0x25, 0x12, 0x28,
	0x20, 0x70, 0x10, 0xa8, 0xec, 0x89, 0xba, 0x28, 0x82, 0xa8, 0x28, 0x05, 0x51, 0xda, 0x85, 0xe5,
	0xcb, 0x68, 0x3c, 0xc4, 0x9e, 0x49, 0x3d, 0x63, 0xd1, 0x74, 0x8b, 0x78, 0x01, 0x9e, 0x80, 0xc7,
	0xe1, 0x19, 0x58, 0xf4, 0x45, 0xd8, 0xa0, 0x71, 0x7c, 0xeb, 0x25, 0x69, 0x69, 0x36, 0xac, 0x92,
	0x99, 0xf3, 0xfb, 0x9f, 0x73, 0xce, 0x37, 0x17, 0x78, 0x70, 0x3c, 0x90, 0x3e, 0x8e, 0x28, 0x67,
	0x2d, 0x21, 0x6d, 0x27, 0xc0, 0x2e, 0xa7, 0xac, 0x25, 0x8f, 0xcc, 0x7e, 0xc4, 0x25, 0x47, 0xb5,
	0x3c, 0x6c, 0x16, 0xe1, 0x7a, 0x8d, 0x70, 0xc2, 0x13, 0x41, 0x4b, 0xfd, 0x1b, 0x6a, 0x1b, 0xdf,
	0x74, 0x98, 0xef, 0x08, 0xd2, 0xa1, 0x4c, 0xee, 0x7f, 0xfe, 0xb0, 0x85, 0xee, 0x42, 0x45, 0x60,
	0xe6, 0xe1, 0xc8, 0xd0, 0xd6, 0xb5, 0xe6, 0x5c, 0x37, 0x1d, 0xa1, 0x7b, 0x30, 0x47, 0x1d, 0xd7,
	0xf2, 0x30, 0xe3, 0xa1, 0x31, 0x95, 0x84, 0x66, 0xa9, 0xe3, 0x6e, 0xa9, 0x31, 0x3a, 0x80, 0x5b,
	0x2e, 0x0f, 0x02, 0x5b, 0xe2, 0xc8, 0x0e, 0x2c, 0x3b, 0xe4, 0x31, 0x93, 0x86, 0xae, 0x44, 0x6d,
	0xf3, 0xd7, 0xc9, 0xda, 0x8d, 0xdf, 0x27, 0x6b, 0x8f, 0x08, 0x95, 0x7e, 0xec, 0x98, 0x2e, 0x0f,
	0x5b, 0x2e, 0x17, 0x21, 0x17, 0xe9, 0xcf, 0x33, 0xe1, 0xf5, 0x5a, 0x72, 0xd0, 0xc7, 0xc2, 0x7c,
	0xc3, 0x64, 0x77, 0xb9, 0x30, 0x7a, 0x9d, 0xf8, 0xa0, 0x8f, 0xb0, 0x18, 0xe1, 0xc3, 0x18, 0x0b,
	0x89, 0x3d, 0xeb, 0x78, 0x20, 0x3d, 0x63, 0xfa, 0x5a, 0xce, 0x0b, 0xb9, 0xcb, 0xfe, 0x40, 0x7a,
	0xe8, 0x15, 0xac, 0xe0, 0xa3, 0x3e, 0x8d, 0x6c, 0x49, 0x39, 0xb3, 0x9c, 0x80, 0xbb, 0x3d, 0xcb,
	0xc7, 0x94, 0xf8, 0xd2, 0x98, 0x59, 0xd7, 0x9a, 0x7a, 0xf7, 0x4e, 0x11, 0x6e, 0xab, 0xe8, 0x76,
	0x12, 0x44, 0x4f, 0x01, 0x79, 0x34, 0xa0, 0xd2, 0xa7, 0x71, 0xb8, 0x69, 0xf5, 0x63, 0xc7, 0xea,
	0xe1, 0x81, 0x51, 0x59, 0xd7, 0x9a, 0xd5, 0xee, 0x72, 0x11, 0x79, 0x1f, 0x3b, 0x6f, 0xf1, 0x00,
	0x3d, 0x84, 0xc5, 0x92, 0x5a, 0x50, 0x62, 0xdc, 0x4c, 0x94, 0x0b, 0xc5, 0xec, 0x2e, 0x25, 0x8d,
	0x2f, 0x70, 0xbb, 0x04, 0xa1, 0x8b, 0x45, 0x9f, 0x33, 0x81, 0xd1, 0x2e, 0x2c, 0x84, 0x94, 0xa9,
	0xba, 0xd3, 0x9e, 0x6a, 0xd7, 0xaa, 0xbc, 0x3a, 0x34, 0x19, 0xf6, 0xb3, 0xf1, 0x73, 0x2a, 0x21,
	0xde, 0x8e, 0x23, 0x76, 0x7d, 0xe2, 0x3b, 0x30, 0xaf, 0x50, 0x4c, 0xc6, 0x1a, 0x94, 0x45, 0x4a,
	0x79, 0x0c, 0x8e, 0xe9, 0x7f, 0xc7, 0x31, 0x73, 0x65, 0x1c, 0x95, 0x8b, 0x70, 0xb0, 0x04, 0x47,
	0xd6, 0xa1, 0x1c, 0xc7, 0x27, 0x58, 0x8a, 0x99, 0x5a, 0x7b, 0x52, 0x20, 0x8b, 0x99, 0x4d, 0x8a,
	0xe4, 0x8f, 0x06, 0xd5, 0x8e, 0x20, 0xef, 0xe8, 0x61, 0x4c, 0x3d, 0x5b, 0x62, 0xb4, 0x0a, 0x10,
	0xa4, 0x03, 0x9e, 0x71, 0x29, 0xcd, 0xa0, 0x0d, 0xa8, 0x4a, 0x3b, 0x22, 0x58, 0x5a, 0xfc, 0x2b,
	0xc3, 0x51, 0x8a, 0x67, 0x7e, 0x38, 0xb7, 0xa3, 0xa6, 0x4e, 0xe3, 0xd3, 0xcf, 0xe0, 0xfb, 0xaf,
	0xba, 0xdd, 0x83, 0x5a, 0xb9, 0xf8, 0xf2, 0xee, 0x17, 0x98, 0x1e, 0x4f, 0xbc, 0xfb, 0x87, 0x26,
	0x69, 0xab, 0x7f, 0x68, 0x80, 0x3a, 0x82, 0x74, 0x31, 0xa1, 0x42, 0xe2, 0x48, 0xf1, 0x55, 0xa9,
	0x8e, 0x3a, 0x04, 0x17, 0x17, 0x3c, 0x35, 0xa2, 0xe0, 0x31, 0x6d, 0xd5, 0xc7, 0xb4, 0xb5, 0xb1,
	0x0b, 0xf5, 0xf3, 0x39, 0xe5, 0x7d, 0xd8, 0x84, 0x95, 0x28, 0x0d, 0x61, 0x2f, 0xcb, 0xc1, 0xf2,
	0x6d, 0xe1, 0xa7, 0xc9, 0xd6, 0x8a, 0xf0, 0x30, 0x91, 0x6d, 0x5b, 0xf8, 0x2f, 0xbe, 0xeb, 0xa0,
	0x77, 0x04, 0x41, 0x7b, 0x30, 0x9b, 0xdf, 0xee, 0x1b, 0xe6, 0x45, 0x4f, 0x83, 0x59, 0xba, 0x7b,
	0xea, 0x8f, 0x2f, 0x95, 0xe4, 0x89, 0xed, 0xc1, 0x6c, 0x7e, 0x8b, 0x8c, 0x76, 0xce, 0x24, 0x63,
	0x9c, 0xcf, 0x9d, 0xb4, 0x03, 0x98, 0x2b, 0x0e, 0x43, 0x63, 0xe4, 0x77, 0xb9, 0xa6, 0xfe, 0xe4,
	0x72, 0x4d, 0x6e, 0x1e, 0xc2, 0xd2, 0x59, 0xfc, 0xcd, 0x91, 0x9f, 0x9f, 0x51, 0xd6, 0x9f, 0x5f,
	0x55, 0x99, 0x2d, 0xd7, 0x5e, 0xdd, 0xbf, 0x5f, 0x3c, 0xd7, 0x47, 0xa7, 0x1e, 0x6c, 0xb5, 0x47,
	0x9d, 0x4a, 0xf2, 0x10, 0xbf, 0xfc, 0x1b, 0x00, 0x00, 0xff, 0xff, 0x60, 0x2c, 0x08, 0x19, 0xd5,
	0x07, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	MintZYTD(ctx context.Context, in *MsgMintZYTD, opts ...grpc.CallOption) (*MsgMintZYTDResponse, error)
	BurnZYTD(ctx context.Context, in *MsgBurnZYTD, opts ...grpc.CallOption) (*MsgBurnZYTDResponse, error)
	Liquidate(ctx context.Context, in *MsgLiquidate, opts ...grpc.CallOption) (*MsgLiquidateResponse, error)
	RegisterZYTDKey(ctx context.Context, in *MsgRegisterZYTDKey, opts ...grpc.CallOption) (*MsgRegisterZYTDKeyResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) MintZYTD(ctx context.Context, in *MsgMintZYTD, opts ...grpc.CallOption) (*MsgMintZYTDResponse, error) {
	out := new(MsgMintZYTDResponse)
	err := c.cc.Invoke(ctx, "/zytherion.stablecoin.Msg/MintZYTD", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) BurnZYTD(ctx context.Context, in *MsgBurnZYTD, opts ...grpc.CallOption) (*MsgBurnZYTDResponse, error) {
	out := new(MsgBurnZYTDResponse)
	err := c.cc.Invoke(ctx, "/zytherion.stablecoin.Msg/BurnZYTD", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) Liquidate(ctx context.Context, in *MsgLiquidate, opts ...grpc.CallOption) (*MsgLiquidateResponse, error) {
	out := new(MsgLiquidateResponse)
	err := c.cc.Invoke(ctx, "/zytherion.stablecoin.Msg/Liquidate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) RegisterZYTDKey(ctx context.Context, in *MsgRegisterZYTDKey, opts ...grpc.CallOption) (*MsgRegisterZYTDKeyResponse, error) {
	out := new(MsgRegisterZYTDKeyResponse)
	err := c.cc.Invoke(ctx, "/zytherion.stablecoin.Msg/RegisterZYTDKey", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	MintZYTD(context.Context, *MsgMintZYTD) (*MsgMintZYTDResponse, error)
	BurnZYTD(context.Context, *MsgBurnZYTD) (*MsgBurnZYTDResponse, error)
	Liquidate(context.Context, *MsgLiquidate) (*MsgLiquidateResponse, error)
	RegisterZYTDKey(context.Context, *MsgRegisterZYTDKey) (*MsgRegisterZYTDKeyResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) MintZYTD(ctx context.Context, req *MsgMintZYTD) (*MsgMintZYTDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MintZYTD not implemented")
}
func (*UnimplementedMsgServer) BurnZYTD(ctx context.Context, req *MsgBurnZYTD) (*MsgBurnZYTDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BurnZYTD not implemented")
}
func (*UnimplementedMsgServer) Liquidate(ctx context.Context, req *MsgLiquidate) (*MsgLiquidateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Liquidate not implemented")
}
func (*UnimplementedMsgServer) RegisterZYTDKey(ctx context.Context, req *MsgRegisterZYTDKey) (*MsgRegisterZYTDKeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterZYTDKey not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_MintZYTD_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgMintZYTD)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).MintZYTD(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/zytherion.stablecoin.Msg/MintZYTD",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).MintZYTD(ctx, req.(*MsgMintZYTD))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_BurnZYTD_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgBurnZYTD)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).BurnZYTD(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/zytherion.stablecoin.Msg/BurnZYTD",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).BurnZYTD(ctx, req.(*MsgBurnZYTD))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_Liquidate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgLiquidate)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).Liquidate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/zytherion.stablecoin.Msg/Liquidate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).Liquidate(ctx, req.(*MsgLiquidate))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_RegisterZYTDKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgRegisterZYTDKey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).RegisterZYTDKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/zytherion.stablecoin.Msg/RegisterZYTDKey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).RegisterZYTDKey(ctx, req.(*MsgRegisterZYTDKey))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "zytherion.stablecoin.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "MintZYTD",
			Handler:    _Msg_MintZYTD_Handler,
		},
		{
			MethodName: "BurnZYTD",
			Handler:    _Msg_BurnZYTD_Handler,
		},
		{
			MethodName: "Liquidate",
			Handler:    _Msg_Liquidate_Handler,
		},
		{
			MethodName: "RegisterZYTDKey",
			Handler:    _Msg_RegisterZYTDKey_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "zytherion/stablecoin/tx.proto",
}
