// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: zytherion/oracle/query.proto

package types

import (
	context "context"
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "github.com/gogo/googleapis/google/api"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type QueryPriceRequest struct {
	Denom                string   `protobuf:"bytes,1,opt,name=denom,proto3" json:"denom,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryPriceRequest) Reset()         { *m = QueryPriceRequest{} }
func (m *QueryPriceRequest) String() string { return proto.CompactTextString(m) }
func (*QueryPriceRequest) ProtoMessage()    {}
func (*QueryPriceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a00395d0953c7f47, []int{0}
}
func (m *QueryPriceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryPriceRequest.Unmarshal(m, b)
}
func (m *QueryPriceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryPriceRequest.Marshal(b, m, deterministic)
}
func (m *QueryPriceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryPriceRequest.Merge(m, src)
}
func (m *QueryPriceRequest) XXX_Size() int {
	return xxx_messageInfo_QueryPriceRequest.Size(m)
}
func (m *QueryPriceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryPriceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryPriceRequest proto.InternalMessageInfo

func (m *QueryPriceRequest) GetDenom() string {
	if m != nil {
		return m.Denom
	}
	return ""
}

type QueryPriceResponse struct {
	Denom                string                                 `protobuf:"bytes,1,opt,name=denom,proto3" json:"denom,omitempty"`
	PriceUsd             github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,2,opt,name=price_usd,json=priceUsd,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"price_usd"`
	Submitter            string                                 `protobuf:"bytes,3,opt,name=submitter,proto3" json:"submitter,omitempty"`
	Height               int64                                  `protobuf:"varint,4,opt,name=height,proto3" json:"height,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                               `json:"-"`
	XXX_unrecognized     []byte                                 `json:"-"`
	XXX_sizecache        int32                                  `json:"-"`
}

func (m *QueryPriceResponse) Reset()         { *m = QueryPriceResponse{} }
func (m *QueryPriceResponse) String() string { return proto.CompactTextString(m) }
func (*QueryPriceResponse) ProtoMessage()    {}
func (*QueryPriceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a00395d0953c7f47, []int{1}
}
func (m *QueryPriceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryPriceResponse.Unmarshal(m, b)
}
func (m *QueryPriceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryPriceResponse.Marshal(b, m, deterministic)
}
func (m *QueryPriceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryPriceResponse.Merge(m, src)
}
func (m *QueryPriceResponse) XXX_Size() int {
	return xxx_messageInfo_QueryPriceResponse.Size(m)
}
func (m *QueryPriceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryPriceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryPriceResponse proto.InternalMessageInfo

func (m *QueryPriceResponse) GetDenom() string {
	if m != nil {
		return m.Denom
	}
	return ""
}

func (m *QueryPriceResponse) GetSubmitter() string {
	if m != nil {
		return m.Submitter
	}
	return ""
}

func (m *QueryPriceResponse) GetHeight() int64 {
	if m != nil {
		return m.Height
	}
	return 0
}

type QueryTWAPRequest struct {
	Denom                string   `protobuf:"bytes,1,opt,name=denom,proto3" json:"denom,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryTWAPRequest) Reset()         { *m = QueryTWAPRequest{} }
func (m *QueryTWAPRequest) String() string { return proto.CompactTextString(m) }
func (*QueryTWAPRequest) ProtoMessage()    {}
func (*QueryTWAPRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a00395d0953c7f47, []int{2}
}
func (m *QueryTWAPRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryTWAPRequest.Unmarshal(m, b)
}
func (m *QueryTWAPRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryTWAPRequest.Marshal(b, m, deterministic)
}
func (m *QueryTWAPRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryTWAPRequest.Merge(m, src)
}
func (m *QueryTWAPRequest) XXX_Size() int {
	return xxx_messageInfo_QueryTWAPRequest.Size(m)
}
func (m *QueryTWAPRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryTWAPRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryTWAPRequest proto.InternalMessageInfo

func (m *QueryTWAPRequest) GetDenom() string {
	if m != nil {
		return m.Denom
	}
	return ""
}

type QueryTWAPResponse struct {
	Denom                string                                 `protobuf:"bytes,1,opt,name=denom,proto3" json:"denom,omitempty"`
	Twap                 github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,2,opt,name=twap,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"twap"`
	WindowStart          int64                                  `protobuf:"varint,3,opt,name=window_start,json=windowStart,proto3" json:"window_start,omitempty"`
	WindowEnd            int64                                  `protobuf:"varint,4,opt,name=window_end,json=windowEnd,proto3" json:"window_end,omitempty"`
	NumSamples           int32                                  `protobuf:"varint,5,opt,name=num_samples,json=numSamples,proto3" json:"num_samples,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                               `json:"-"`
	XXX_unrecognized     []byte                                 `json:"-"`
	XXX_sizecache        int32                                  `json:"-"`
}

func (m *QueryTWAPResponse) Reset()         { *m = QueryTWAPResponse{} }
func (m *QueryTWAPResponse) String() string { return proto.CompactTextString(m) }
func (*QueryTWAPResponse) ProtoMessage()    {}
func (*QueryTWAPResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a00395d0953c7f47, []int{3}
}
func (m *QueryTWAPResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryTWAPResponse.Unmarshal(m, b)
}
func (m *QueryTWAPResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryTWAPResponse.Marshal(b, m, deterministic)
}
func (m *QueryTWAPResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryTWAPResponse.Merge(m, src)
}
func (m *QueryTWAPResponse) XXX_Size() int {
	return xxx_messageInfo_QueryTWAPResponse.Size(m)
}
func (m *QueryTWAPResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryTWAPResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryTWAPResponse proto.InternalMessageInfo

func (m *QueryTWAPResponse) GetDenom() string {
	if m != nil {
		return m.Denom
	}
	return ""
}

func (m *QueryTWAPResponse) GetWindowStart() int64 {
	if m != nil {
		return m.WindowStart
	}
	return 0
}

func (m *QueryTWAPResponse) GetWindowEnd() int64 {
	if m != nil {
		return m.WindowEnd
	}
	return 0
}

func (m *QueryTWAPResponse) GetNumSamples() int32 {
	if m != nil {
		return m.NumSamples
	}
	return 0
}

type QueryAllPricesRequest struct {
	Denom                string   `protobuf:"bytes,1,opt,name=denom,proto3" json:"denom,omitempty"`
	FromHeight           int64    `protobuf:"varint,2,opt,name=from_height,json=fromHeight,proto3" json:"from_height,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryAllPricesRequest) Reset()         { *m = QueryAllPricesRequest{} }
func (m *QueryAllPricesRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllPricesRequest) ProtoMessage()    {}
func (*QueryAllPricesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a00395d0953c7f47, []int{4}
}
func (m *QueryAllPricesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryAllPricesRequest.Unmarshal(m, b)
}
func (m *QueryAllPricesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryAllPricesRequest.Marshal(b, m, deterministic)
}
func (m *QueryAllPricesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllPricesRequest.Merge(m, src)
}
func (m *QueryAllPricesRequest) XXX_Size() int {
	return xxx_messageInfo_QueryAllPricesRequest.Size(m)
}
func (m *QueryAllPricesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllPricesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllPricesRequest proto.InternalMessageInfo

func (m *QueryAllPricesRequest) GetDenom() string {
	if m != nil {
		return m.Denom
	}
	return ""
}

func (m *QueryAllPricesRequest) GetFromHeight() int64 {
	if m != nil {
		return m.FromHeight
	}
	return 0
}

type QueryAllPricesResponse struct {
	Prices               []*QueryPriceResponse `protobuf:"bytes,1,rep,name=prices,proto3" json:"prices,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *QueryAllPricesResponse) Reset()         { *m = QueryAllPricesResponse{} }
func (m *QueryAllPricesResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllPricesResponse) ProtoMessage()    {}
func (*QueryAllPricesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a00395d0953c7f47, []int{5}
}
func (m *QueryAllPricesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryAllPricesResponse.Unmarshal(m, b)
}
func (m *QueryAllPricesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryAllPricesResponse.Marshal(b, m, deterministic)
}
func (m *QueryAllPricesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllPricesResponse.Merge(m, src)
}
func (m *QueryAllPricesResponse) XXX_Size() int {
	return xxx_messageInfo_QueryAllPricesResponse.Size(m)
}
func (m *QueryAllPricesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllPricesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllPricesResponse proto.InternalMessageInfo

func (m *QueryAllPricesResponse) GetPrices() []*QueryPriceResponse {
	if m != nil {
		return m.Prices
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryPriceRequest)(nil), "zytherion.oracle.QueryPriceRequest")
	proto.RegisterType((*QueryPriceResponse)(nil), "zytherion.oracle.QueryPriceResponse")
	proto.RegisterType((*QueryTWAPRequest)(nil), "zytherion.oracle.QueryTWAPRequest")
	proto.RegisterType((*QueryTWAPResponse)(nil), "zytherion.oracle.QueryTWAPResponse")
	proto.RegisterType((*QueryAllPricesRequest)(nil), "zytherion.oracle.QueryAllPricesRequest")
	proto.RegisterType((*QueryAllPricesResponse)(nil), "zytherion.oracle.QueryAllPricesResponse")
}

func init() { proto.RegisterFile("zytherion/oracle/query.proto", fileDescriptor_a00395d0953c7f47) }

var fileDescriptor_a00395d0953c7f47 = []byte{
	// 531 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0xcb, 0x6e, 0xd3, 0x40,
	0x14, 0xc5, 0x49, 0x13, 0xe1, 0x1b, 0x84, 0xca, 0xa8, 0x54, 0x96, 0x15, 0x88, 0xeb, 0xa2, 0xd6,
	0x2c, 0xb0, 0xa5, 0xb2, 0x65, 0xd3, 0x08, 0x24, 0x24, 0x24, 0x54, 0x5c, 0x1e, 0x12, 0x9b, 0xc8,
	0xb1, 0x07, 0xc7, 0xc2, 0x9e, 0x71, 0x3d, 0x63, 0x85, 0xf0, 0x90, 0x10, 0x7b, 0x56, 0x6c, 0xf8,
	0x09, 0xfe, 0x83, 0x25, 0x12, 0x3b, 0x16, 0x5d, 0xf1, 0x21, 0x68, 0x1e, 0x24, 0x25, 0x21, 0x06,
	0x75, 0x95, 0xcc, 0xbd, 0x67, 0xce, 0xb9, 0xe7, 0xcc, 0x4d, 0xa0, 0xff, 0x7a, 0xc6, 0x27, 0xb8,
	0xca, 0x28, 0x09, 0x68, 0x15, 0xc5, 0x39, 0x0e, 0x4e, 0x6a, 0x5c, 0xcd, 0xfc, 0xb2, 0xa2, 0x9c,
	0xa2, 0xcd, 0x79, 0xd7, 0x57, 0x5d, 0x7b, 0x2b, 0xa5, 0x29, 0x95, 0xcd, 0x40, 0x7c, 0x53, 0x38,
	0xbb, 0x9f, 0x52, 0x9a, 0xe6, 0x38, 0x88, 0xca, 0x2c, 0x88, 0x08, 0xa1, 0x3c, 0xe2, 0x19, 0x25,
	0x4c, 0x75, 0xdd, 0x9b, 0x70, 0xe5, 0x91, 0x20, 0x3d, 0xaa, 0xb2, 0x18, 0x87, 0xf8, 0xa4, 0xc6,
	0x8c, 0xa3, 0x2d, 0xe8, 0x24, 0x98, 0xd0, 0xc2, 0x32, 0x1c, 0xc3, 0x33, 0x43, 0x75, 0x70, 0xbf,
	0x18, 0x80, 0xce, 0x62, 0x59, 0x49, 0x09, 0xc3, 0x7f, 0x07, 0xa3, 0x07, 0x60, 0x96, 0x02, 0x36,
	0xaa, 0x59, 0x62, 0xb5, 0x44, 0x67, 0xe8, 0x7f, 0x3d, 0x1d, 0x5c, 0xf8, 0x71, 0x3a, 0xd8, 0x4b,
	0x33, 0x3e, 0xa9, 0xc7, 0x7e, 0x4c, 0x8b, 0x20, 0xa6, 0xac, 0xa0, 0x4c, 0x7f, 0xdc, 0x62, 0xc9,
	0xcb, 0x80, 0xcf, 0x4a, 0xcc, 0xfc, 0xbb, 0x38, 0x0e, 0x2f, 0x4a, 0x82, 0x27, 0x2c, 0x41, 0x7d,
	0x30, 0x59, 0x3d, 0x2e, 0x32, 0xce, 0x71, 0x65, 0xb5, 0xa5, 0xcc, 0xa2, 0x80, 0xb6, 0xa1, 0x3b,
	0xc1, 0x59, 0x3a, 0xe1, 0xd6, 0x86, 0x63, 0x78, 0xed, 0x50, 0x9f, 0x5c, 0x0f, 0x36, 0xe5, 0xb8,
	0x8f, 0x9f, 0x1d, 0x1e, 0x35, 0x3b, 0xfb, 0x66, 0xe8, 0x14, 0x14, 0xb4, 0xd1, 0xd8, 0x10, 0x36,
	0xf8, 0x34, 0x2a, 0xcf, 0xe9, 0x49, 0xde, 0x45, 0x3b, 0x70, 0x69, 0x9a, 0x91, 0x84, 0x4e, 0x47,
	0x8c, 0x47, 0x15, 0x97, 0x96, 0xda, 0x61, 0x4f, 0xd5, 0x8e, 0x45, 0x09, 0x5d, 0x03, 0xd0, 0x10,
	0x4c, 0x12, 0x6d, 0xcc, 0x54, 0x95, 0x7b, 0x24, 0x41, 0x03, 0xe8, 0x91, 0xba, 0x18, 0xb1, 0xa8,
	0x28, 0x73, 0xcc, 0xac, 0x8e, 0x63, 0x78, 0x9d, 0x10, 0x48, 0x5d, 0x1c, 0xab, 0x8a, 0xfb, 0x10,
	0xae, 0x4a, 0x47, 0x87, 0x79, 0x2e, 0x9f, 0x8b, 0x35, 0x26, 0x20, 0xf8, 0x5e, 0x54, 0xb4, 0x18,
	0xe9, 0x20, 0x5b, 0x52, 0x0f, 0x44, 0xe9, 0xbe, 0x0a, 0xf3, 0x29, 0x6c, 0x2f, 0xf3, 0xe9, 0x98,
	0xee, 0x40, 0x57, 0x3e, 0x14, 0xb3, 0x0c, 0xa7, 0xed, 0xf5, 0x0e, 0x6e, 0xf8, 0xcb, 0x8b, 0xe9,
	0xaf, 0x6e, 0x4d, 0xa8, 0xef, 0x1c, 0x7c, 0x6e, 0x43, 0x47, 0xb6, 0xd1, 0x7b, 0x03, 0x60, 0x01,
	0x44, 0xbb, 0xcd, 0x34, 0xd2, 0x8c, 0xfd, 0x5f, 0x5a, 0xee, 0xfe, 0x87, 0xef, 0x3f, 0x3f, 0xb5,
	0x76, 0xd0, 0x20, 0x58, 0xf9, 0x41, 0xc9, 0x29, 0x82, 0x37, 0x32, 0x84, 0x77, 0xe8, 0x2d, 0x98,
	0xf3, 0x35, 0x40, 0xee, 0x1a, 0xee, 0x33, 0xeb, 0x64, 0xef, 0x36, 0x62, 0xb4, 0xfc, 0x9e, 0x94,
	0x77, 0xd0, 0xf5, 0x55, 0x79, 0xb1, 0x0d, 0x73, 0xf5, 0x8f, 0x06, 0x5c, 0xfe, 0x33, 0x63, 0xb4,
	0xbf, 0x86, 0x7f, 0xf9, 0x55, 0x6d, 0xef, 0xdf, 0x40, 0x3d, 0x8d, 0x27, 0xa7, 0x71, 0x91, 0xb3,
	0x26, 0x0c, 0xf6, 0x7b, 0x9e, 0xa1, 0xfd, 0xdc, 0x5a, 0x40, 0x5e, 0xcd, 0x47, 0x16, 0xbb, 0x3c,
	0xee, 0xca, 0x7f, 0x8f, 0xdb, 0xbf, 0x02, 0x00, 0x00, 0xff, 0xff, 0x4c, 0x49, 0xc1, 0x9d, 0xa3,
	0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	QueryPrice(ctx context.Context, in *QueryPriceRequest, opts ...grpc.CallOption) (*QueryPriceResponse, error)
	QueryTWAP(ctx context.Context, in *QueryTWAPRequest, opts ...grpc.CallOption) (*QueryTWAPResponse, error)
	QueryAllPrices(ctx context.Context, in *QueryAllPricesRequest, opts ...grpc.CallOption) (*QueryAllPricesResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) QueryPrice(ctx context.Context, in *QueryPriceRequest, opts ...grpc.CallOption) (*QueryPriceResponse, error) {
	out := new(QueryPriceResponse)
	err := c.cc.Invoke(ctx, "/zytherion.oracle.Query/QueryPrice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) QueryTWAP(ctx context.Context, in *QueryTWAPRequest, opts ...grpc.CallOption) (*QueryTWAPResponse, error) {
	out := new(QueryTWAPResponse)
	err := c.cc.Invoke(ctx, "/zytherion.oracle.Query/QueryTWAP", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) QueryAllPrices(ctx context.Context, in *QueryAllPricesRequest, opts ...grpc.CallOption) (*QueryAllPricesResponse, error) {
	out := new(QueryAllPricesResponse)
	err := c.cc.Invoke(ctx, "/zytherion.oracle.Query/QueryAllPrices", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	QueryPrice(context.Context, *QueryPriceRequest) (*QueryPriceResponse, error)
	QueryTWAP(context.Context, *QueryTWAPRequest) (*QueryTWAPResponse, error)
	QueryAllPrices(context.Context, *QueryAllPricesRequest) (*QueryAllPricesResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) QueryPrice(ctx context.Context, req *QueryPriceRequest) (*QueryPriceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryPrice not implemented")
}
func (*UnimplementedQueryServer) QueryTWAP(ctx context.Context, req *QueryTWAPRequest) (*QueryTWAPResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryTWAP not implemented")
}
func (*UnimplementedQueryServer) QueryAllPrices(ctx context.Context, req *QueryAllPricesRequest) (*QueryAllPricesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryAllPrices not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_QueryPrice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryPriceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).QueryPrice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/zytherion.oracle.Query/QueryPrice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).QueryPrice(ctx, req.(*QueryPriceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_QueryTWAP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryTWAPRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).QueryTWAP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/zytherion.oracle.Query/QueryTWAP",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).QueryTWAP(ctx, req.(*QueryTWAPRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_QueryAllPrices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllPricesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).QueryAllPrices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/zytherion.oracle.Query/QueryAllPrices",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).QueryAllPrices(ctx, req.(*QueryAllPricesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "zytherion.oracle.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "QueryPrice",
			Handler:    _Query_QueryPrice_Handler,
		},
		{
			MethodName: "QueryTWAP",
			Handler:    _Query_QueryTWAP_Handler,
		},
		{
			MethodName: "QueryAllPrices",
			Handler:    _Query_QueryAllPrices_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "zytherion/oracle/query.proto",
}
