// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: zytherion/oracle/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// MsgSubmitPrice submits a price feed entry.
type MsgSubmitPrice struct {
	Submitter            string                                 `protobuf:"bytes,1,opt,name=submitter,proto3" json:"submitter,omitempty"`
	Denom                string                                 `protobuf:"bytes,2,opt,name=denom,proto3" json:"denom,omitempty"`
	PriceUsd             github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,3,opt,name=price_usd,json=priceUsd,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"price_usd"`
	XXX_NoUnkeyedLiteral struct{}                               `json:"-"`
	XXX_unrecognized     []byte                                 `json:"-"`
	XXX_sizecache        int32                                  `json:"-"`
}

func (m *MsgSubmitPrice) Reset()         { *m = MsgSubmitPrice{} }
func (m *MsgSubmitPrice) String() string { return proto.CompactTextString(m) }
func (*MsgSubmitPrice) ProtoMessage()    {}
func (*MsgSubmitPrice) Descriptor() ([]byte, []int) {
	return fileDescriptor_e4fe304fedf5c19e, []int{0}
}
func (m *MsgSubmitPrice) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgSubmitPrice.Unmarshal(m, b)
}
func (m *MsgSubmitPrice) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgSubmitPrice.Marshal(b, m, deterministic)
}
func (m *MsgSubmitPrice) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSubmitPrice.Merge(m, src)
}
func (m *MsgSubmitPrice) XXX_Size() int {
	return xxx_messageInfo_MsgSubmitPrice.Size(m)
}
func (m *MsgSubmitPrice) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSubmitPrice.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSubmitPrice proto.InternalMessageInfo

func (m *MsgSubmitPrice) GetSubmitter() string {
	if m != nil {
		return m.Submitter
	}
	return ""
}

func (m *MsgSubmitPrice) GetDenom() string {
	if m != nil {
		return m.Denom
	}
	return ""
}

type MsgSubmitPriceResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgSubmitPriceResponse) Reset()         { *m = MsgSubmitPriceResponse{} }
func (m *MsgSubmitPriceResponse) String() string { return proto.CompactTextString(m) }
func (*MsgSubmitPriceResponse) ProtoMessage()    {}
func (*MsgSubmitPriceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e4fe304fedf5c19e, []int{1}
}
func (m *MsgSubmitPriceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgSubmitPriceResponse.Unmarshal(m, b)
}
func (m *MsgSubmitPriceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgSubmitPriceResponse.Marshal(b, m, deterministic)
}
func (m *MsgSubmitPriceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSubmitPriceResponse.Merge(m, src)
}
func (m *MsgSubmitPriceResponse) XXX_Size() int {
	return xxx_messageInfo_MsgSubmitPriceResponse.Size(m)
}
func (m *MsgSubmitPriceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSubmitPriceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSubmitPriceResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgSubmitPrice)(nil), "zytherion.oracle.MsgSubmitPrice")
	proto.RegisterType((*MsgSubmitPriceResponse)(nil), "zytherion.oracle.MsgSubmitPriceResponse")
}

func init() { proto.RegisterFile("zytherion/oracle/tx.proto", fileDescriptor_e4fe304fedf5c19e) }

var fileDescriptor_e4fe304fedf5c19e = []byte{
	// 247 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0xac, 0xaa, 0x2c, 0xc9,
	0x48, 0x2d, 0xca, 0xcc, 0xcf, 0xd3, 0xcf, 0x2f, 0x4a, 0x4c, 0xce, 0x49, 0xd5, 0x2f, 0xa9, 0xd0,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x12, 0x80, 0x4b, 0xe9, 0x41, 0xa4, 0xa4, 0x44, 0xd2, 0xf3,
	0xd3, 0xf3, 0xc1, 0x92, 0xfa, 0x20, 0x16, 0x44, 0x9d, 0xd2, 0x44, 0x46, 0x2e, 0x3e, 0xdf, 0xe2,
	0xf4, 0xe0, 0xd2, 0xa4, 0xdc, 0xcc, 0x92, 0x80, 0xa2, 0xcc, 0xe4, 0x54, 0x21, 0x19, 0x2e, 0xce,
	0x62, 0x30, 0xb7, 0x24, 0xb5, 0x48, 0x82, 0x51, 0x81, 0x51, 0x83, 0x33, 0x08, 0x21, 0x20, 0x24,
	0xc2, 0xc5, 0x9a, 0x92, 0x9a, 0x97, 0x9f, 0x2b, 0xc1, 0x04, 0x96, 0x81, 0x70, 0x84, 0xbc, 0xb9,
	0x38, 0x0b, 0x40, 0x9a, 0xe3, 0x4b, 0x8b, 0x53, 0x24, 0x98, 0x41, 0x32, 0x4e, 0x7a, 0x27, 0xee,
	0xc9, 0x33, 0xdc, 0xba, 0x27, 0xaf, 0x96, 0x9e, 0x59, 0x92, 0x51, 0x9a, 0xa4, 0x97, 0x9c, 0x9f,
	0xab, 0x9f, 0x9c, 0x5f, 0x9c, 0x9b, 0x5f, 0x0c, 0xa5, 0x74, 0x8b, 0x53, 0xb2, 0xf5, 0x4b, 0x2a,
	0x0b, 0x52, 0x8b, 0xf5, 0x5c, 0x52, 0x93, 0x83, 0x38, 0xc0, 0x06, 0x84, 0x16, 0xa7, 0x28, 0x49,
	0x70, 0x89, 0xa1, 0x3a, 0x29, 0x28, 0xb5, 0xb8, 0x20, 0x3f, 0xaf, 0x38, 0xd5, 0x28, 0x81, 0x8b,
	0xd9, 0xb7, 0x38, 0x5d, 0x28, 0x92, 0x8b, 0x1b, 0xd9, 0xc1, 0x0a, 0x7a, 0xe8, 0x9e, 0xd5, 0x43,
	0xd5, 0x2f, 0xa5, 0x41, 0x48, 0x05, 0xcc, 0x06, 0x27, 0xa9, 0x28, 0x09, 0x44, 0xa0, 0x56, 0xc0,
	0x83, 0x15, 0xe4, 0xca, 0x24, 0x36, 0x70, 0x90, 0x19, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0xcb,
	0xb8, 0x60, 0xe3, 0x77, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	SubmitPrice(ctx context.Context, in *MsgSubmitPrice, opts ...grpc.CallOption) (*MsgSubmitPriceResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) SubmitPrice(ctx context.Context, in *MsgSubmitPrice, opts ...grpc.CallOption) (*MsgSubmitPriceResponse, error) {
	out := new(MsgSubmitPriceResponse)
	err := c.cc.Invoke(ctx, "/zytherion.oracle.Msg/SubmitPrice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	SubmitPrice(context.Context, *MsgSubmitPrice) (*MsgSubmitPriceResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) SubmitPrice(ctx context.Context, req *MsgSubmitPrice) (*MsgSubmitPriceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitPrice not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_SubmitPrice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSubmitPrice)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).SubmitPrice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/zytherion.oracle.Msg/SubmitPrice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).SubmitPrice(ctx, req.(*MsgSubmitPrice))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "zytherion.oracle.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitPrice",
			Handler:    _Msg_SubmitPrice_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "zytherion/oracle/tx.proto",
}
