// engine.go — CGo wrapper for the tfhe_c Rust library.
//
// This file provides the Go API for TFHE (Fully Homomorphic Encryption)
// operations on 32-bit unsigned integers (FheUint32).
//
// # Build Requirements
//
//  1. Rust toolchain installed (rustup, cargo)
//  2. tfhe_c compiled: `cd x/privacy/tfhe/tfhe_c && cargo build --release`
//  3. The static lib must exist at the path referenced by LDFLAGS below.
//
// Build with: go build -tags tfhe_cgo ./...
// (Without -tags tfhe_cgo, engine_stub.go is used instead — all TFHE ops return ErrTFHEDisabled)
//
// # CGo Linking
//
// The CGo directives below instruct the Go toolchain to:
//   - Include the local cgo_bridge.h header
//   - Link the compiled libtfhe_c.a static library
//   - Link platform math/pthread libs required by the Rust binary
//
// # Thread Safety
//
// Homomorphic operations (Add, Sub, MulScalar) are routed through the
// OS-thread-pinned TFHEWorkerPool. Each worker goroutine is permanently
// pinned to one OS thread via runtime.LockOSThread(), so Rust's
// thread-local ServerKey set by set_server_key() is always stable.
//
// Encrypt and Decrypt use the ClientKey only — they do NOT call
// set_server_key(), so they are safe to call from any goroutine without
// pool routing or a mutex.
//
// GenerateKeys is a one-time slow operation and keeps its own local mutex.

package tfhe

/*
#cgo CFLAGS: -I${SRCDIR}
#cgo LDFLAGS: -L${SRCDIR}/tfhe_c/target/release -ltfhe_c -lm -ldl -lpthread
#include "cgo_bridge.h"
#include <stdlib.h>
*/
import "C"
import (
	"errors"
	"fmt"
	"sync"
	"unsafe"
)

// ── Constants ──────────────────────────────────────────────────────────────────

// Note: CiphertextMaxBytes is defined in erasure.go to avoid CGo dependency.
// Use tfhe.CiphertextMaxBytes from that file directly.

// ── KeyPair ───────────────────────────────────────────────────────────────────

// TFHEKeyPair holds the serialized TFHE ClientKey and ServerKey.
// ClientKey: used for Encrypt/Decrypt (must stay private).
// ServerKey: used for homomorphic evaluation (can be public/shared).
type TFHEKeyPair struct {
	ClientKey []byte
	ServerKey []byte
}

// ── Key Generation ────────────────────────────────────────────────────────────

// keygenMu serialises GenerateKeys calls only.
// Key generation is a one-time slow operation (~10–60s); the local mutex
// prevents concurrent keygen calls from racing on shared C state.
var keygenMu sync.Mutex

// GenerateKeys generates a fresh TFHE ClientKey + ServerKey pair.
//
// WARNING: Key generation is SLOW (~10–60 seconds depending on CPU).
// This should only be called once per node, with keys persisted to disk.
func GenerateKeys() (*TFHEKeyPair, error) {
	keygenMu.Lock()
	defer keygenMu.Unlock()

	ckMaxLen := C.tfhe_client_key_max_bytes()
	skMaxLen := C.tfhe_server_key_max_bytes()

	ckBuf := C.malloc(C.size_t(ckMaxLen))
	skBuf := C.malloc(C.size_t(skMaxLen))
	defer C.free(ckBuf)
	defer C.free(skBuf)

	var ckLen, skLen C.uint64_t

	ret := C.tfhe_keygen(
		(*C.uint8_t)(ckBuf), &ckLen,
		(*C.uint8_t)(skBuf), &skLen,
	)
	if ret != 0 {
		return nil, errors.New("tfhe: key generation failed in Rust library")
	}

	ck := C.GoBytes(ckBuf, C.int(ckLen))
	sk := C.GoBytes(skBuf, C.int(skLen))

	return &TFHEKeyPair{
		ClientKey: ck,
		ServerKey: sk,
	}, nil
}

// ── Encrypt ───────────────────────────────────────────────────────────────────

// EncryptUint32 encrypts a 32-bit unsigned integer using the TFHE ClientKey.
//
// Returns a serialised FheUint32 ciphertext (~16–21 KB in practice).
// The caller must supply the serialized ClientKey bytes from TFHEKeyPair.ClientKey.
//
// Thread safety: safe to call concurrently. Encrypt uses only the ClientKey
// and does NOT call set_server_key(), so no OS-thread pinning is required.
func EncryptUint32(clientKey []byte, plaintext uint32) ([]byte, error) {
	if len(clientKey) == 0 {
		return nil, errors.New("tfhe: client key is empty")
	}

	ctBuf := C.malloc(C.size_t(CiphertextMaxBytes))
	defer C.free(ctBuf)

	ckPtr := (*C.uint8_t)(unsafe.Pointer(&clientKey[0]))

	ctLen := C.tfhe_encrypt_u32(
		ckPtr, C.uint64_t(len(clientKey)),
		C.uint32_t(plaintext),
		(*C.uint8_t)(ctBuf), C.uint64_t(CiphertextMaxBytes),
	)
	if ctLen < 0 {
		return nil, fmt.Errorf("tfhe: encryption failed (Rust returned %d)", int(ctLen))
	}

	return C.GoBytes(ctBuf, C.int(ctLen)), nil
}

// EncryptWithPublicKey encrypts a uint32 using a TFHE CompressedPublicKey.
//
// FIX 2 (CVE-ZYTH-002): Unlike EncryptUint32 (which uses the node's ClientKey),
// this function uses the USER's own registered PublicKey. The resulting ciphertext
// can only be decrypted by the user holding the matching ClientKey — not the node.
//
// pubKey must be a serialised tfhe::CompressedPublicKey generated by the user
// and registered on-chain via MsgRegisterUserTFHEPublicKey.
//
// Thread safety: safe to call concurrently. PublicKey encryption does not
// require set_server_key(), so no OS-thread pinning is needed.
func EncryptWithPublicKey(pubKey []byte, plaintext uint32) ([]byte, error) {
	if len(pubKey) == 0 {
		return nil, errors.New("tfhe: public key is empty")
	}

	ctBuf := C.malloc(C.size_t(CiphertextMaxBytes))
	defer C.free(ctBuf)

	pkPtr := (*C.uint8_t)(unsafe.Pointer(&pubKey[0]))

	ctLen := C.tfhe_encrypt_u32_pk(
		pkPtr, C.uint64_t(len(pubKey)),
		C.uint32_t(plaintext),
		(*C.uint8_t)(ctBuf), C.uint64_t(CiphertextMaxBytes),
	)
	if ctLen < 0 {
		return nil, fmt.Errorf("tfhe: PublicKey encryption failed (Rust returned %d)", int(ctLen))
	}

	return C.GoBytes(ctBuf, C.int(ctLen)), nil
}

// EncryptWithServerKey encrypts a uint32 using the server key configuration
// to produce a ciphertext compatible with homomorphic evaluation.
//
// This is used internally for the transfer Sub operation where the node needs
// to create a ciphertext of the transfer amount to subtract from the sender's
// balance (which is evaluated under the shared server key context).
//
// Note: the result ciphertext can be decrypted by anyone with the ClientKey
// that matches the ServerKey. For true per-user privacy, all paths should
// eventually use EncryptWithPublicKey. This function is a transitional bridge.
func EncryptWithServerKey(serverKey []byte, plaintext uint32) ([]byte, error) {
	// In the current TFHE-rs setup, the node holds the ClientKey alongside the
	// ServerKey (both generated together). We use the node's ClientKey to create
	// an evaluation-compatible ciphertext for homomorphic Sub.
	//
	// This is the REMAINING centralization risk acknowledged in v0.5.2 docs.
	// Full user-key isolation for the Sub path requires threshold re-encryption
	// or ZK range proofs — planned for v0.8.
	_, nodeClientKey, err := cachedNodeClientKey()
	if err != nil {
		return nil, fmt.Errorf("tfhe: EncryptWithServerKey: %w", err)
	}
	return EncryptUint32(nodeClientKey, plaintext)
}

// cachedNodeClientKey returns the node's client key from the EnsureNodeKeys cache.
// This is used ONLY for the Sub intermediate ciphertext — the sender's balance
// was encrypted under THEIR public key, but the sub operand needs to match
// the shared server key context. See comments in EncryptWithServerKey.
func cachedNodeClientKey() ([]byte, []byte, error) {
	nodeKeysMu.Lock()
	defer nodeKeysMu.Unlock()
	if len(nodeClientKeyCache) == 0 {
		return nil, nil, errors.New("tfhe: node keys not initialised — call EnsureNodeKeys first")
	}
	return nodeClientKeyCache, nodeClientKeyCache, nil
}


// ── Homomorphic Add ───────────────────────────────────────────────────────────

// AddUint32 performs homomorphic addition of two FheUint32 ciphertexts.
//
//	result_ct = Enc(a) + Enc(b)   →   when decrypted: Dec(result_ct) == (a + b) mod 2^32
//
// The ServerKey is required to evaluate the circuit. Both ciphertexts must
// have been encrypted under the same configuration.
//
// Thread safety: routes through the OS-thread-pinned worker pool when
// available. Falls back to direct execution if the pool is not initialised
// (e.g. during startup or unit tests).
func AddUint32(serverKey, ct1, ct2 []byte) ([]byte, error) {
	if len(serverKey) == 0 {
		return nil, errors.New("tfhe: server key is empty")
	}
	if len(ct1) == 0 || len(ct2) == 0 {
		return nil, errors.New("tfhe: ciphertext inputs must not be empty")
	}

	pool := GetPool()
	if pool == nil {
		// Pool not initialized — fall back to direct (serialized) call.
		// This happens during startup before InitWorkerPool is called.
		return addUint32Direct(serverKey, ct1, ct2)
	}

	var result []byte
	var opErr error
	err := pool.Submit(func() error {
		result, opErr = addUint32Direct(serverKey, ct1, ct2)
		return opErr
	})
	if err != nil {
		return nil, err
	}
	return result, nil
}

// addUint32Direct is the raw CGo call, executed within a pool worker's
// pinned OS thread. No mutex needed — thread-local server key is safe.
func addUint32Direct(serverKey, ct1, ct2 []byte) ([]byte, error) {
	resultBuf := C.malloc(C.size_t(CiphertextMaxBytes))
	defer C.free(resultBuf)

	skPtr := (*C.uint8_t)(unsafe.Pointer(&serverKey[0]))
	c1Ptr := (*C.uint8_t)(unsafe.Pointer(&ct1[0]))
	c2Ptr := (*C.uint8_t)(unsafe.Pointer(&ct2[0]))

	resLen := C.tfhe_add_u32(
		skPtr, C.uint64_t(len(serverKey)),
		c1Ptr, C.uint64_t(len(ct1)),
		c2Ptr, C.uint64_t(len(ct2)),
		(*C.uint8_t)(resultBuf), C.uint64_t(CiphertextMaxBytes),
	)
	if resLen < 0 {
		return nil, fmt.Errorf("tfhe: homomorphic add failed (Rust returned %d)", int(resLen))
	}
	return C.GoBytes(resultBuf, C.int(resLen)), nil
}

// ── Homomorphic Sub ───────────────────────────────────────────────────────────

// SubUint32 performs homomorphic subtraction of two FheUint32 ciphertexts.
//
//	result_ct = Enc(a) - Enc(b)   →   when decrypted: Dec(result_ct) == (a - b) mod 2^32
//
// Note: wraps around at 0, same as u32 arithmetic in Rust/Go.
// Use only when caller guarantees a ≥ b to avoid underflow confusion.
// For Confidential ZYTD transfers, the caller is responsible for ensuring
// the sender balance exceeds the transfer amount (range proof required in v0.8+).
//
// Thread safety: routes through the OS-thread-pinned worker pool when available.
func SubUint32(serverKey, ct1, ct2 []byte) ([]byte, error) {
	if len(serverKey) == 0 {
		return nil, errors.New("tfhe: server key is empty")
	}
	if len(ct1) == 0 || len(ct2) == 0 {
		return nil, errors.New("tfhe: ciphertext inputs must not be empty")
	}

	pool := GetPool()
	if pool == nil {
		return subUint32Direct(serverKey, ct1, ct2)
	}

	var result []byte
	var opErr error
	err := pool.Submit(func() error {
		result, opErr = subUint32Direct(serverKey, ct1, ct2)
		return opErr
	})
	if err != nil {
		return nil, err
	}
	return result, nil
}

// subUint32Direct is the raw CGo call for homomorphic subtraction,
// executed within a pool worker's pinned OS thread.
func subUint32Direct(serverKey, ct1, ct2 []byte) ([]byte, error) {
	resultBuf := C.malloc(C.size_t(CiphertextMaxBytes))
	defer C.free(resultBuf)

	skPtr := (*C.uint8_t)(unsafe.Pointer(&serverKey[0]))
	c1Ptr := (*C.uint8_t)(unsafe.Pointer(&ct1[0]))
	c2Ptr := (*C.uint8_t)(unsafe.Pointer(&ct2[0]))

	resLen := C.tfhe_sub_u32(
		skPtr, C.uint64_t(len(serverKey)),
		c1Ptr, C.uint64_t(len(ct1)),
		c2Ptr, C.uint64_t(len(ct2)),
		(*C.uint8_t)(resultBuf), C.uint64_t(CiphertextMaxBytes),
	)
	if resLen < 0 {
		return nil, fmt.Errorf("tfhe: homomorphic sub failed (Rust returned %d)", int(resLen))
	}
	return C.GoBytes(resultBuf, C.int(resLen)), nil
}

// ── Scalar Multiply ───────────────────────────────────────────────────────────

// MultiplyScalarUint32 multiplies a ciphertext by an unencrypted scalar.
//
//	result_ct = Enc(a) * scalar   →   when decrypted: Dec(result_ct) == (a * scalar) mod 2^32
//
// Thread safety: routes through the OS-thread-pinned worker pool when available.
func MultiplyScalarUint32(serverKey, ct []byte, scalar uint32) ([]byte, error) {
	if len(serverKey) == 0 {
		return nil, errors.New("tfhe: server key is empty")
	}
	if len(ct) == 0 {
		return nil, errors.New("tfhe: ciphertext must not be empty")
	}

	pool := GetPool()
	if pool == nil {
		return multiplyScalarDirect(serverKey, ct, scalar)
	}

	var result []byte
	var opErr error
	err := pool.Submit(func() error {
		result, opErr = multiplyScalarDirect(serverKey, ct, scalar)
		return opErr
	})
	if err != nil {
		return nil, err
	}
	return result, nil
}

// multiplyScalarDirect is the raw CGo call for scalar multiplication,
// executed within a pool worker's pinned OS thread.
func multiplyScalarDirect(serverKey, ct []byte, scalar uint32) ([]byte, error) {
	resultBuf := C.malloc(C.size_t(CiphertextMaxBytes))
	defer C.free(resultBuf)

	skPtr := (*C.uint8_t)(unsafe.Pointer(&serverKey[0]))
	ctPtr := (*C.uint8_t)(unsafe.Pointer(&ct[0]))

	resLen := C.tfhe_mul_scalar_u32(
		skPtr, C.uint64_t(len(serverKey)),
		ctPtr, C.uint64_t(len(ct)),
		C.uint32_t(scalar),
		(*C.uint8_t)(resultBuf), C.uint64_t(CiphertextMaxBytes),
	)
	if resLen < 0 {
		return nil, fmt.Errorf("tfhe: scalar multiply failed (Rust returned %d)", int(resLen))
	}
	return C.GoBytes(resultBuf, C.int(resLen)), nil
}

// ── Decrypt ───────────────────────────────────────────────────────────────────

// DecryptUint32 decrypts a FheUint32 ciphertext using the ClientKey.
//
// Returns the plaintext uint32 value on success.
//
// Thread safety: safe to call concurrently. Decrypt uses only the ClientKey
// and does NOT call set_server_key(), so no OS-thread pinning is required.
func DecryptUint32(clientKey, ciphertext []byte) (uint32, error) {
	if len(clientKey) == 0 {
		return 0, errors.New("tfhe: client key is empty")
	}
	if len(ciphertext) == 0 {
		return 0, errors.New("tfhe: ciphertext is empty")
	}

	ckPtr := (*C.uint8_t)(unsafe.Pointer(&clientKey[0]))
	ctPtr := (*C.uint8_t)(unsafe.Pointer(&ciphertext[0]))

	result := C.tfhe_decrypt_u32(
		ckPtr, C.uint64_t(len(clientKey)),
		ctPtr, C.uint64_t(len(ciphertext)),
	)
	if result < 0 {
		return 0, fmt.Errorf("tfhe: decryption failed (Rust returned %d)", int(result))
	}

	return uint32(result), nil
}
